// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/golang/protobuf/ptypes/timestamp/timestamp.proto

//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:4
package timestamp

//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:4
import (
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:4
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:4
)
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:4
import (
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:4
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:4
)

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
)

//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:15
type Timestamp = timestamppb.Timestamp

var File_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto protoreflect.FileDescriptor

var file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x3b, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_goTypes = []interface{}{}
var file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_depIdxs = []int32{
	0,
	0,
	0,
	0,
	0,
}

func init()	{ file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_init() }
func file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_init() {
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:43
	_go_fuzz_dep_.CoverTab[68012]++
														if File_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto != nil {
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:44
		_go_fuzz_dep_.CoverTab[68014]++
															return
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:45
		// _ = "end of CoverTab[68014]"
	} else {
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:46
		_go_fuzz_dep_.CoverTab[68015]++
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:46
		// _ = "end of CoverTab[68015]"
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:46
	}
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:46
	// _ = "end of CoverTab[68012]"
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:46
	_go_fuzz_dep_.CoverTab[68013]++
														type x struct{}
														out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath:	reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor:	file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_rawDesc,
			NumEnums:	0,
			NumMessages:	0,
			NumExtensions:	0,
			NumServices:	0,
		},
		GoTypes:		file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_goTypes,
		DependencyIndexes:	file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_depIdxs,
	}.Build()
														File_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto = out.File
														file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_rawDesc = nil
														file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_goTypes = nil
														file_github_com_golang_protobuf_ptypes_timestamp_timestamp_proto_depIdxs = nil
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:63
	// _ = "end of CoverTab[68013]"
}

//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:64
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/github.com/golang/protobuf@v1.5.3/ptypes/timestamp/timestamp.pb.go:64
var _ = _go_fuzz_dep_.CoverTab
