{{/*
# Copyright 2020-present Open Networking Foundation

# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
*/}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: upf
  labels:
{{ tuple "upf" . | include "omec-user-plane.metadata_labels" | indent 4 }}
data:
{{- range $key, $value := .Values.config.upf.cfgFiles }}
  {{ $key }}: {{ toJson $value | quote }}
{{- end }}
  bessd-poststart.sh: |
{{ tuple "bin/_bessd-poststart.sh.tpl" . | include "omec-user-plane.template" | indent 4 }}
