{{/*
# Copyright 2020-present Open Networking Foundation

# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
*/}}

---
apiVersion: v1
kind: Service
metadata:
  name: upf
  labels:
{{ tuple "upf" . | include "omec-user-plane.metadata_labels" | indent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalIp }}
  externalIPs:
    - {{ .Values.service.externalIp }}
{{- end }}
  selector:
{{ tuple "upf" . | include "omec-user-plane.metadata_labels" | indent 4 }}
  ports:
  - name: pfcp
    protocol: UDP
    port: 8805
---
apiVersion: v1
kind: Service
metadata:
  name: upf-http
  labels:
{{ tuple "upf" . | include "omec-user-plane.metadata_labels" | indent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalIp }}
  externalIPs:
    - {{ .Values.service.externalIp }}
{{- end }}
  selector:
{{ tuple "upf" . | include "omec-user-plane.metadata_labels" | indent 4 }}
  ports:
  - name: bess-web
    protocol: TCP
    port: 8000
  - name: prometheus-exporter
    protocol: TCP
    port: 8080
