---
# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

apiVersion: v1
description: Thingsboard IoT Platform
name: thingsboard-iot-platform
icon: https://guide.opencord.org/logos/cord.svg

version: 0.1.1
