// Protocol Buffers - Google's data interchange format
// Copyright 2008 Google Inc.  All rights reserved.
// https://developers.google.com/protocol-buffers/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/protobuf/duration.proto

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// Package durationpb contains generated types for google/protobuf/duration.proto.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// The Duration message represents a signed span of time.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// # Conversion to a Go Duration
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// The AsDuration method can be used to convert a Duration message to a
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// standard Go time.Duration value:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//	d := dur.AsDuration()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//	... // make use of d as a time.Duration
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// Converting to a time.Duration is a common operation so that the extensive
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// set of time-based operations provided by the time package can be leveraged.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// See https://golang.org/pkg/time for more information.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// The AsDuration method performs the conversion on a best-effort basis.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// Durations with denormal values (e.g., nanoseconds beyond -99999999 and
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// +99999999, inclusive; or seconds and nanoseconds with opposite signs)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// are normalized during the conversion to a time.Duration. To manually check for
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// invalid Duration per the documented limitations in duration.proto,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// additionally call the CheckValid method:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//	if err := dur.CheckValid(); err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//		... // handle error
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// Note that the documented limitations in duration.proto does not protect a
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// Duration from overflowing the representable range of a time.Duration in Go.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// The AsDuration method uses saturation arithmetic such that an overflow clamps
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// the resulting value to the closest representable value (e.g., math.MaxInt64
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// for positive overflow and math.MinInt64 for negative overflow).
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// # Conversion from a Go Duration
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// The durationpb.New function can be used to construct a Duration message
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
// from a standard Go time.Duration value:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//	dur := durationpb.New(d)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:34
//	... // make use of d as a *durationpb.Duration
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:77
package durationpb

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:77
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:77
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:77
)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:77
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:77
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:77
)

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	math "math"
	reflect "reflect"
	sync "sync"
	time "time"
)

// A Duration represents a signed, fixed-length span of time represented
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// as a count of seconds and fractions of seconds at nanosecond
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// resolution. It is independent of any calendar and concepts like "day"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// or "month". It is related to Timestamp in that the difference between
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// two Timestamp values is a Duration and it can be added or subtracted
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// from a Timestamp. Range is approximately +-10,000 years.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// # Examples
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// Example 1: Compute Duration from two Timestamps in pseudo code.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	Timestamp start = ...;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	Timestamp end = ...;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	Duration duration = ...;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	duration.seconds = end.seconds - start.seconds;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	duration.nanos = end.nanos - start.nanos;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	if (duration.seconds < 0 && duration.nanos > 0) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	  duration.seconds += 1;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	  duration.nanos -= 1000000000;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	} else if (duration.seconds > 0 && duration.nanos < 0) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	  duration.seconds -= 1;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	  duration.nanos += 1000000000;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// Example 2: Compute Timestamp from Timestamp + Duration in pseudo code.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	Timestamp start = ...;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	Duration duration = ...;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	Timestamp end = ...;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	end.seconds = start.seconds + duration.seconds;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	end.nanos = start.nanos + duration.nanos;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	if (end.nanos < 0) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	  end.seconds -= 1;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	  end.nanos += 1000000000;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	} else if (end.nanos >= 1000000000) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	  end.seconds += 1;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	  end.nanos -= 1000000000;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// Example 3: Compute Duration from datetime.timedelta in Python.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	td = datetime.timedelta(days=3, minutes=10)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	duration = Duration()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//	duration.FromTimedelta(td)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// # JSON Mapping
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// In JSON format, the Duration type is encoded as a string rather than an
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// object, where the string ends in the suffix "s" (indicating seconds) and
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// is preceded by the number of seconds, with nanoseconds expressed as
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// fractional seconds. For example, 3 seconds with 0 nanoseconds should be
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// encoded in JSON format as "3s", while 3 seconds and 1 nanosecond should
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// be expressed in JSON format as "3.000000001s", and 3 seconds and 1
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:88
// microsecond should be expressed in JSON format as "3.000001s".
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:148
type Duration struct {
	state		protoimpl.MessageState
	sizeCache	protoimpl.SizeCache
	unknownFields	protoimpl.UnknownFields

	// Signed seconds of the span of time. Must be from -315,576,000,000
	// to +315,576,000,000 inclusive. Note: these bounds are computed from:
	// 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
	Seconds	int64	`protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Signed fractions of a second at nanosecond resolution of the span
	// of time. Durations less than one second are represented with a 0
	// `seconds` field and a positive or negative `nanos` field. For durations
	// of one second or more, a non-zero value for the `nanos` field must be
	// of the same sign as the `seconds` field. Must be from -999,999,999
	// to +999,999,999 inclusive.
	Nanos	int32	`protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
}

// New constructs a new Duration from the provided time.Duration.
func New(d time.Duration) *Duration {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:167
	_go_fuzz_dep_.CoverTab[67884]++
														nanos := d.Nanoseconds()
														secs := nanos / 1e9
														nanos -= secs * 1e9
														return &Duration{Seconds: int64(secs), Nanos: int32(nanos)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:171
	// _ = "end of CoverTab[67884]"
}

// AsDuration converts x to a time.Duration,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:174
// returning the closest duration value in the event of overflow.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:176
func (x *Duration) AsDuration() time.Duration {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:176
	_go_fuzz_dep_.CoverTab[67885]++
														secs := x.GetSeconds()
														nanos := x.GetNanos()
														d := time.Duration(secs) * time.Second
														overflow := d/time.Second != time.Duration(secs)
														d += time.Duration(nanos) * time.Nanosecond
														overflow = overflow || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
		_go_fuzz_dep_.CoverTab[67887]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
		return (secs < 0 && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
			_go_fuzz_dep_.CoverTab[67888]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
			return nanos < 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
			// _ = "end of CoverTab[67888]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
		}() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
			_go_fuzz_dep_.CoverTab[67889]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
			return d > 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
			// _ = "end of CoverTab[67889]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
		}())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
		// _ = "end of CoverTab[67887]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:182
	}()
														overflow = overflow || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
		_go_fuzz_dep_.CoverTab[67890]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
		return (secs > 0 && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
			_go_fuzz_dep_.CoverTab[67891]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
			return nanos > 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
			// _ = "end of CoverTab[67891]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
		}() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
			_go_fuzz_dep_.CoverTab[67892]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
			return d < 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
			// _ = "end of CoverTab[67892]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
		}())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
		// _ = "end of CoverTab[67890]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:183
	}()
														if overflow {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:184
		_go_fuzz_dep_.CoverTab[67893]++
															switch {
		case secs < 0:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:186
			_go_fuzz_dep_.CoverTab[67894]++
																return time.Duration(math.MinInt64)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:187
			// _ = "end of CoverTab[67894]"
		case secs > 0:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:188
			_go_fuzz_dep_.CoverTab[67895]++
																return time.Duration(math.MaxInt64)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:189
			// _ = "end of CoverTab[67895]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:189
		default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:189
			_go_fuzz_dep_.CoverTab[67896]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:189
			// _ = "end of CoverTab[67896]"
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:190
		// _ = "end of CoverTab[67893]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:191
		_go_fuzz_dep_.CoverTab[67897]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:191
		// _ = "end of CoverTab[67897]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:191
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:191
	// _ = "end of CoverTab[67885]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:191
	_go_fuzz_dep_.CoverTab[67886]++
														return d
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:192
	// _ = "end of CoverTab[67886]"
}

// IsValid reports whether the duration is valid.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:195
// It is equivalent to CheckValid == nil.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:197
func (x *Duration) IsValid() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:197
	_go_fuzz_dep_.CoverTab[67898]++
														return x.check() == 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:198
	// _ = "end of CoverTab[67898]"
}

// CheckValid returns an error if the duration is invalid.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:201
// In particular, it checks whether the value is within the range of
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:201
// -10000 years to +10000 years inclusive.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:201
// An error is reported for a nil Duration.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:205
func (x *Duration) CheckValid() error {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:205
	_go_fuzz_dep_.CoverTab[67899]++
														switch x.check() {
	case invalidNil:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:207
		_go_fuzz_dep_.CoverTab[67900]++
															return protoimpl.X.NewError("invalid nil Duration")
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:208
		// _ = "end of CoverTab[67900]"
	case invalidUnderflow:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:209
		_go_fuzz_dep_.CoverTab[67901]++
															return protoimpl.X.NewError("duration (%v) exceeds -10000 years", x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:210
		// _ = "end of CoverTab[67901]"
	case invalidOverflow:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:211
		_go_fuzz_dep_.CoverTab[67902]++
															return protoimpl.X.NewError("duration (%v) exceeds +10000 years", x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:212
		// _ = "end of CoverTab[67902]"
	case invalidNanosRange:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:213
		_go_fuzz_dep_.CoverTab[67903]++
															return protoimpl.X.NewError("duration (%v) has out-of-range nanos", x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:214
		// _ = "end of CoverTab[67903]"
	case invalidNanosSign:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:215
		_go_fuzz_dep_.CoverTab[67904]++
															return protoimpl.X.NewError("duration (%v) has seconds and nanos with different signs", x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:216
		// _ = "end of CoverTab[67904]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:217
		_go_fuzz_dep_.CoverTab[67905]++
															return nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:218
		// _ = "end of CoverTab[67905]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:219
	// _ = "end of CoverTab[67899]"
}

const (
	_	= iota
	invalidNil
	invalidUnderflow
	invalidOverflow
	invalidNanosRange
	invalidNanosSign
)

func (x *Duration) check() uint {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:231
	_go_fuzz_dep_.CoverTab[67906]++
														const absDuration = 315576000000	// 10000yr * 365.25day/yr * 24hr/day * 60min/hr * 60sec/min
														secs := x.GetSeconds()
														nanos := x.GetNanos()
														switch {
	case x == nil:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:236
		_go_fuzz_dep_.CoverTab[67907]++
															return invalidNil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:237
		// _ = "end of CoverTab[67907]"
	case secs < -absDuration:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:238
		_go_fuzz_dep_.CoverTab[67908]++
															return invalidUnderflow
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:239
		// _ = "end of CoverTab[67908]"
	case secs > +absDuration:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:240
		_go_fuzz_dep_.CoverTab[67909]++
															return invalidOverflow
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:241
		// _ = "end of CoverTab[67909]"
	case nanos <= -1e9 || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:242
		_go_fuzz_dep_.CoverTab[67913]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:242
		return nanos >= +1e9
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:242
		// _ = "end of CoverTab[67913]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:242
	}():
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:242
		_go_fuzz_dep_.CoverTab[67910]++
															return invalidNanosRange
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:243
		// _ = "end of CoverTab[67910]"
	case (secs > 0 && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
		_go_fuzz_dep_.CoverTab[67914]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
		return nanos < 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
		// _ = "end of CoverTab[67914]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
	}()) || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
		_go_fuzz_dep_.CoverTab[67915]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
		return (secs < 0 && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
			_go_fuzz_dep_.CoverTab[67916]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
			return nanos > 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
			// _ = "end of CoverTab[67916]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
		}())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
		// _ = "end of CoverTab[67915]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
	}():
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:244
		_go_fuzz_dep_.CoverTab[67911]++
															return invalidNanosSign
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:245
		// _ = "end of CoverTab[67911]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:246
		_go_fuzz_dep_.CoverTab[67912]++
															return 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:247
		// _ = "end of CoverTab[67912]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:248
	// _ = "end of CoverTab[67906]"
}

func (x *Duration) Reset() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:251
	_go_fuzz_dep_.CoverTab[67917]++
														*x = Duration{}
														if protoimpl.UnsafeEnabled {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:253
		_go_fuzz_dep_.CoverTab[67918]++
															mi := &file_google_protobuf_duration_proto_msgTypes[0]
															ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
															ms.StoreMessageInfo(mi)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:256
		// _ = "end of CoverTab[67918]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:257
		_go_fuzz_dep_.CoverTab[67919]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:257
		// _ = "end of CoverTab[67919]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:257
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:257
	// _ = "end of CoverTab[67917]"
}

func (x *Duration) String() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:260
	_go_fuzz_dep_.CoverTab[67920]++
														return protoimpl.X.MessageStringOf(x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:261
	// _ = "end of CoverTab[67920]"
}

func (*Duration) ProtoMessage()	{ _go_fuzz_dep_.CoverTab[67921]++; // _ = "end of CoverTab[67921]" }

func (x *Duration) ProtoReflect() protoreflect.Message {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:266
	_go_fuzz_dep_.CoverTab[67922]++
														mi := &file_google_protobuf_duration_proto_msgTypes[0]
														if protoimpl.UnsafeEnabled && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:268
		_go_fuzz_dep_.CoverTab[67924]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:268
		return x != nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:268
		// _ = "end of CoverTab[67924]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:268
	}() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:268
		_go_fuzz_dep_.CoverTab[67925]++
															ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
															if ms.LoadMessageInfo() == nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:270
			_go_fuzz_dep_.CoverTab[67927]++
																ms.StoreMessageInfo(mi)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:271
			// _ = "end of CoverTab[67927]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:272
			_go_fuzz_dep_.CoverTab[67928]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:272
			// _ = "end of CoverTab[67928]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:272
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:272
		// _ = "end of CoverTab[67925]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:272
		_go_fuzz_dep_.CoverTab[67926]++
															return ms
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:273
		// _ = "end of CoverTab[67926]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:274
		_go_fuzz_dep_.CoverTab[67929]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:274
		// _ = "end of CoverTab[67929]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:274
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:274
	// _ = "end of CoverTab[67922]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:274
	_go_fuzz_dep_.CoverTab[67923]++
														return mi.MessageOf(x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:275
	// _ = "end of CoverTab[67923]"
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:279
	_go_fuzz_dep_.CoverTab[67930]++
														return file_google_protobuf_duration_proto_rawDescGZIP(), []int{0}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:280
	// _ = "end of CoverTab[67930]"
}

func (x *Duration) GetSeconds() int64 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:283
	_go_fuzz_dep_.CoverTab[67931]++
														if x != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:284
		_go_fuzz_dep_.CoverTab[67933]++
															return x.Seconds
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:285
		// _ = "end of CoverTab[67933]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:286
		_go_fuzz_dep_.CoverTab[67934]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:286
		// _ = "end of CoverTab[67934]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:286
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:286
	// _ = "end of CoverTab[67931]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:286
	_go_fuzz_dep_.CoverTab[67932]++
														return 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:287
	// _ = "end of CoverTab[67932]"
}

func (x *Duration) GetNanos() int32 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:290
	_go_fuzz_dep_.CoverTab[67935]++
														if x != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:291
		_go_fuzz_dep_.CoverTab[67937]++
															return x.Nanos
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:292
		// _ = "end of CoverTab[67937]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:293
		_go_fuzz_dep_.CoverTab[67938]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:293
		// _ = "end of CoverTab[67938]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:293
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:293
	// _ = "end of CoverTab[67935]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:293
	_go_fuzz_dep_.CoverTab[67936]++
														return 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:294
	// _ = "end of CoverTab[67936]"
}

var File_google_protobuf_duration_proto protoreflect.FileDescriptor

var file_google_protobuf_duration_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x22, 0x3a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6e, 0x6f, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x42, 0x83, 0x01,
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x0d, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x31, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x2f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0xf8, 0x01, 0x01, 0xa2, 0x02, 0x03, 0x47,
	0x50, 0x42, 0xaa, 0x02, 0x1e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x57, 0x65, 0x6c, 0x6c, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_protobuf_duration_proto_rawDescOnce	sync.Once
	file_google_protobuf_duration_proto_rawDescData	= file_google_protobuf_duration_proto_rawDesc
)

func file_google_protobuf_duration_proto_rawDescGZIP() []byte {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:323
	_go_fuzz_dep_.CoverTab[67939]++
														file_google_protobuf_duration_proto_rawDescOnce.Do(func() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:324
		_go_fuzz_dep_.CoverTab[67941]++
															file_google_protobuf_duration_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_protobuf_duration_proto_rawDescData)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:325
		// _ = "end of CoverTab[67941]"
	})
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:326
	// _ = "end of CoverTab[67939]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:326
	_go_fuzz_dep_.CoverTab[67940]++
														return file_google_protobuf_duration_proto_rawDescData
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:327
	// _ = "end of CoverTab[67940]"
}

var file_google_protobuf_duration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_protobuf_duration_proto_goTypes = []interface{}{
	(*Duration)(nil),
}
var file_google_protobuf_duration_proto_depIdxs = []int32{
	0,
	0,
	0,
	0,
	0,
}

func init()	{ file_google_protobuf_duration_proto_init() }
func file_google_protobuf_duration_proto_init() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:343
	_go_fuzz_dep_.CoverTab[67942]++
														if File_google_protobuf_duration_proto != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:344
		_go_fuzz_dep_.CoverTab[67945]++
															return
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:345
		// _ = "end of CoverTab[67945]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:346
		_go_fuzz_dep_.CoverTab[67946]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:346
		// _ = "end of CoverTab[67946]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:346
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:346
	// _ = "end of CoverTab[67942]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:346
	_go_fuzz_dep_.CoverTab[67943]++
														if !protoimpl.UnsafeEnabled {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:347
		_go_fuzz_dep_.CoverTab[67947]++
															file_google_protobuf_duration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:348
			_go_fuzz_dep_.CoverTab[67948]++
																switch v := v.(*Duration); i {
			case 0:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:350
				_go_fuzz_dep_.CoverTab[67949]++
																	return &v.state
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:351
				// _ = "end of CoverTab[67949]"
			case 1:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:352
				_go_fuzz_dep_.CoverTab[67950]++
																	return &v.sizeCache
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:353
				// _ = "end of CoverTab[67950]"
			case 2:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:354
				_go_fuzz_dep_.CoverTab[67951]++
																	return &v.unknownFields
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:355
				// _ = "end of CoverTab[67951]"
			default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:356
				_go_fuzz_dep_.CoverTab[67952]++
																	return nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:357
				// _ = "end of CoverTab[67952]"
			}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:358
			// _ = "end of CoverTab[67948]"
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:359
		// _ = "end of CoverTab[67947]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:360
		_go_fuzz_dep_.CoverTab[67953]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:360
		// _ = "end of CoverTab[67953]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:360
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:360
	// _ = "end of CoverTab[67943]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:360
	_go_fuzz_dep_.CoverTab[67944]++
														type x struct{}
														out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath:	reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor:	file_google_protobuf_duration_proto_rawDesc,
			NumEnums:	0,
			NumMessages:	1,
			NumExtensions:	0,
			NumServices:	0,
		},
		GoTypes:		file_google_protobuf_duration_proto_goTypes,
		DependencyIndexes:	file_google_protobuf_duration_proto_depIdxs,
		MessageInfos:		file_google_protobuf_duration_proto_msgTypes,
	}.Build()
														File_google_protobuf_duration_proto = out.File
														file_google_protobuf_duration_proto_rawDesc = nil
														file_google_protobuf_duration_proto_goTypes = nil
														file_google_protobuf_duration_proto_depIdxs = nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:378
	// _ = "end of CoverTab[67944]"
}

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:379
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/durationpb/duration.pb.go:379
var _ = _go_fuzz_dep_.CoverTab
