// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.1
// source: api/asn1/v1/asn1.proto

//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:7
package asn1

//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:7
import (
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:7
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:7
)
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:7
import (
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:7
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:7
)

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_	= protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_	= protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BitString struct {
	state		protoimpl.MessageState
	sizeCache	protoimpl.SizeCache
	unknownFields	protoimpl.UnknownFields

	Value	[]byte	`protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Len	uint32	`protobuf:"varint,2,opt,name=len,json=length,proto3" json:"len,omitempty"`
}

func (x *BitString) Reset() {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:32
	_go_fuzz_dep_.CoverTab[171017]++
														*x = BitString{}
														if protoimpl.UnsafeEnabled {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:34
		_go_fuzz_dep_.CoverTab[171018]++
															mi := &file_api_asn1_v1_asn1_proto_msgTypes[0]
															ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
															ms.StoreMessageInfo(mi)
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:37
		// _ = "end of CoverTab[171018]"
	} else {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:38
		_go_fuzz_dep_.CoverTab[171019]++
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:38
		// _ = "end of CoverTab[171019]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:38
	}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:38
	// _ = "end of CoverTab[171017]"
}

func (x *BitString) String() string {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:41
	_go_fuzz_dep_.CoverTab[171020]++
														return protoimpl.X.MessageStringOf(x)
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:42
	// _ = "end of CoverTab[171020]"
}

func (*BitString) ProtoMessage()	{ _go_fuzz_dep_.CoverTab[171021]++; // _ = "end of CoverTab[171021]" }

func (x *BitString) ProtoReflect() protoreflect.Message {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:47
	_go_fuzz_dep_.CoverTab[171022]++
														mi := &file_api_asn1_v1_asn1_proto_msgTypes[0]
														if protoimpl.UnsafeEnabled && func() bool {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:49
		_go_fuzz_dep_.CoverTab[171024]++
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:49
		return x != nil
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:49
		// _ = "end of CoverTab[171024]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:49
	}() {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:49
		_go_fuzz_dep_.CoverTab[171025]++
															ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
															if ms.LoadMessageInfo() == nil {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:51
			_go_fuzz_dep_.CoverTab[171027]++
																ms.StoreMessageInfo(mi)
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:52
			// _ = "end of CoverTab[171027]"
		} else {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:53
			_go_fuzz_dep_.CoverTab[171028]++
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:53
			// _ = "end of CoverTab[171028]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:53
		}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:53
		// _ = "end of CoverTab[171025]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:53
		_go_fuzz_dep_.CoverTab[171026]++
															return ms
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:54
		// _ = "end of CoverTab[171026]"
	} else {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:55
		_go_fuzz_dep_.CoverTab[171029]++
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:55
		// _ = "end of CoverTab[171029]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:55
	}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:55
	// _ = "end of CoverTab[171022]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:55
	_go_fuzz_dep_.CoverTab[171023]++
														return mi.MessageOf(x)
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:56
	// _ = "end of CoverTab[171023]"
}

// Deprecated: Use BitString.ProtoReflect.Descriptor instead.
func (*BitString) Descriptor() ([]byte, []int) {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:60
	_go_fuzz_dep_.CoverTab[171030]++
														return file_api_asn1_v1_asn1_proto_rawDescGZIP(), []int{0}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:61
	// _ = "end of CoverTab[171030]"
}

func (x *BitString) GetValue() []byte {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:64
	_go_fuzz_dep_.CoverTab[171031]++
														if x != nil {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:65
		_go_fuzz_dep_.CoverTab[171033]++
															return x.Value
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:66
		// _ = "end of CoverTab[171033]"
	} else {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:67
		_go_fuzz_dep_.CoverTab[171034]++
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:67
		// _ = "end of CoverTab[171034]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:67
	}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:67
	// _ = "end of CoverTab[171031]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:67
	_go_fuzz_dep_.CoverTab[171032]++
														return nil
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:68
	// _ = "end of CoverTab[171032]"
}

func (x *BitString) GetLen() uint32 {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:71
	_go_fuzz_dep_.CoverTab[171035]++
														if x != nil {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:72
		_go_fuzz_dep_.CoverTab[171037]++
															return x.Len
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:73
		// _ = "end of CoverTab[171037]"
	} else {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:74
		_go_fuzz_dep_.CoverTab[171038]++
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:74
		// _ = "end of CoverTab[171038]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:74
	}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:74
	// _ = "end of CoverTab[171035]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:74
	_go_fuzz_dep_.CoverTab[171036]++
														return 0
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:75
	// _ = "end of CoverTab[171036]"
}

var File_api_asn1_v1_asn1_proto protoreflect.FileDescriptor

var file_api_asn1_v1_asn1_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x73, 0x6e, 0x31, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x73,
	0x6e, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x73, 0x6e, 0x31, 0x2e, 0x76,
	0x31, 0x22, 0x36, 0x0a, 0x09, 0x42, 0x69, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x13, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6e, 0x6f, 0x73, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x2f, 0x6f, 0x6e, 0x6f, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x2d, 0x67, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x73, 0x6e, 0x31, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x73, 0x6e, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_asn1_v1_asn1_proto_rawDescOnce	sync.Once
	file_api_asn1_v1_asn1_proto_rawDescData	= file_api_asn1_v1_asn1_proto_rawDesc
)

func file_api_asn1_v1_asn1_proto_rawDescGZIP() []byte {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:98
	_go_fuzz_dep_.CoverTab[171039]++
														file_api_asn1_v1_asn1_proto_rawDescOnce.Do(func() {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:99
		_go_fuzz_dep_.CoverTab[171041]++
															file_api_asn1_v1_asn1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_asn1_v1_asn1_proto_rawDescData)
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:100
		// _ = "end of CoverTab[171041]"
	})
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:101
	// _ = "end of CoverTab[171039]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:101
	_go_fuzz_dep_.CoverTab[171040]++
														return file_api_asn1_v1_asn1_proto_rawDescData
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:102
	// _ = "end of CoverTab[171040]"
}

var file_api_asn1_v1_asn1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_asn1_v1_asn1_proto_goTypes = []interface{}{
	(*BitString)(nil),
}
var file_api_asn1_v1_asn1_proto_depIdxs = []int32{
	0,
	0,
	0,
	0,
	0,
}

func init()	{ file_api_asn1_v1_asn1_proto_init() }
func file_api_asn1_v1_asn1_proto_init() {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:118
	_go_fuzz_dep_.CoverTab[171042]++
														if File_api_asn1_v1_asn1_proto != nil {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:119
		_go_fuzz_dep_.CoverTab[171045]++
															return
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:120
		// _ = "end of CoverTab[171045]"
	} else {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:121
		_go_fuzz_dep_.CoverTab[171046]++
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:121
		// _ = "end of CoverTab[171046]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:121
	}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:121
	// _ = "end of CoverTab[171042]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:121
	_go_fuzz_dep_.CoverTab[171043]++
														if !protoimpl.UnsafeEnabled {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:122
		_go_fuzz_dep_.CoverTab[171047]++
															file_api_asn1_v1_asn1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:123
			_go_fuzz_dep_.CoverTab[171048]++
																switch v := v.(*BitString); i {
			case 0:
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:125
				_go_fuzz_dep_.CoverTab[171049]++
																	return &v.state
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:126
				// _ = "end of CoverTab[171049]"
			case 1:
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:127
				_go_fuzz_dep_.CoverTab[171050]++
																	return &v.sizeCache
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:128
				// _ = "end of CoverTab[171050]"
			case 2:
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:129
				_go_fuzz_dep_.CoverTab[171051]++
																	return &v.unknownFields
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:130
				// _ = "end of CoverTab[171051]"
			default:
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:131
				_go_fuzz_dep_.CoverTab[171052]++
																	return nil
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:132
				// _ = "end of CoverTab[171052]"
			}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:133
			// _ = "end of CoverTab[171048]"
		}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:134
		// _ = "end of CoverTab[171047]"
	} else {
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:135
		_go_fuzz_dep_.CoverTab[171053]++
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:135
		// _ = "end of CoverTab[171053]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:135
	}
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:135
	// _ = "end of CoverTab[171043]"
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:135
	_go_fuzz_dep_.CoverTab[171044]++
														type x struct{}
														out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath:	reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor:	file_api_asn1_v1_asn1_proto_rawDesc,
			NumEnums:	0,
			NumMessages:	1,
			NumExtensions:	0,
			NumServices:	0,
		},
		GoTypes:		file_api_asn1_v1_asn1_proto_goTypes,
		DependencyIndexes:	file_api_asn1_v1_asn1_proto_depIdxs,
		MessageInfos:		file_api_asn1_v1_asn1_proto_msgTypes,
	}.Build()
														File_api_asn1_v1_asn1_proto = out.File
														file_api_asn1_v1_asn1_proto_rawDesc = nil
														file_api_asn1_v1_asn1_proto_goTypes = nil
														file_api_asn1_v1_asn1_proto_depIdxs = nil
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:153
	// _ = "end of CoverTab[171044]"
}

//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:154
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/github.com/onosproject/onos-lib-go@v0.8.13/api/asn1/v1/asn1/asn1.pb.go:154
var _ = _go_fuzz_dep_.CoverTab
