// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Package protoreflect provides interfaces to dynamically manipulate messages.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// This package includes type descriptors which describe the structure of types
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// defined in proto source files and value interfaces which provide the
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// ability to examine and manipulate the contents of messages.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// # Protocol Buffer Descriptors
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Protobuf descriptors (e.g., EnumDescriptor or MessageDescriptor)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// are immutable objects that represent protobuf type information.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// They are wrappers around the messages declared in descriptor.proto.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Protobuf descriptors alone lack any information regarding Go types.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Enums and messages generated by this module implement Enum and ProtoMessage,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// where the Descriptor and ProtoReflect.Descriptor accessors respectively
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// return the protobuf descriptor for the values.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// The protobuf descriptor interfaces are not meant to be implemented by
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// user code since they might need to be extended in the future to support
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// additions to the protobuf language.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// The "google.golang.org/protobuf/reflect/protodesc" package converts between
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// google.protobuf.DescriptorProto messages and protobuf descriptors.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// # Go Type Descriptors
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// A type descriptor (e.g., EnumType or MessageType) is a constructor for
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// a concrete Go type that represents the associated protobuf descriptor.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// There is commonly a one-to-one relationship between protobuf descriptors and
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Go type descriptors, but it can potentially be a one-to-many relationship.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Enums and messages generated by this module implement Enum and ProtoMessage,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// where the Type and ProtoReflect.Type accessors respectively
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// return the protobuf descriptor for the values.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// The "google.golang.org/protobuf/types/dynamicpb" package can be used to
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// create Go type descriptors from protobuf descriptors.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// # Value Interfaces
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// The Enum and Message interfaces provide a reflective view over an
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// enum or message instance. For enums, it provides the ability to retrieve
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// the enum value number for any concrete enum type. For messages, it provides
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// the ability to access or manipulate fields of the message.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// To convert a proto.Message to a protoreflect.Message, use the
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// former's ProtoReflect method. Since the ProtoReflect method is new to the
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// v2 message interface, it may not be present on older message implementations.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// The "github.com/golang/protobuf/proto".MessageReflect function can be used
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// to obtain a reflective view on older messages.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// # Relationships
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// The following diagrams demonstrate the relationships between
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// various types declared in this package.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	                       ┌───────────────────────────────────┐
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	                       V                                   │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	   ┌────────────── New(n) ─────────────┐                   │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	   │                                   │                   │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	   │      ┌──── Descriptor() ──┐       │  ┌── Number() ──┐ │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	   │      │                    V       V  │              V │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	╔════════════╗  ╔════════════════╗  ╔════════╗  ╔════════════╗
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	║  EnumType  ║  ║ EnumDescriptor ║  ║  Enum  ║  ║ EnumNumber ║
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	╚════════════╝  ╚════════════════╝  ╚════════╝  ╚════════════╝
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	      Λ           Λ                   │ │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	      │           └─── Descriptor() ──┘ │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	      │                                 │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	      └────────────────── Type() ───────┘
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// • An EnumType describes a concrete Go enum type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// It has an EnumDescriptor and can construct an Enum instance.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// • An EnumDescriptor describes an abstract protobuf enum type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// • An Enum is a concrete enum instance. Generated enums implement Enum.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	  ┌──────────────── New() ─────────────────┐
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	  │                                        │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	  │         ┌─── Descriptor() ─────┐       │   ┌── Interface() ───┐
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	  │         │                      V       V   │                  V
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	╔═════════════╗  ╔═══════════════════╗  ╔═════════╗  ╔══════════════╗
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	║ MessageType ║  ║ MessageDescriptor ║  ║ Message ║  ║ ProtoMessage ║
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	╚═════════════╝  ╚═══════════════════╝  ╚═════════╝  ╚══════════════╝
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	       Λ           Λ                      │ │  Λ                  │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	       │           └──── Descriptor() ────┘ │  └─ ProtoReflect() ─┘
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	       │                                    │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	       └─────────────────── Type() ─────────┘
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// • A MessageType describes a concrete Go message type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// It has a MessageDescriptor and can construct a Message instance.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Just as how Go's reflect.Type is a reflective description of a Go type,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// a MessageType is a reflective description of a Go type for a protobuf message.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// • A MessageDescriptor describes an abstract protobuf message type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// It has no understanding of Go types. In order to construct a MessageType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// from just a MessageDescriptor, you can consider looking up the message type
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// in the global registry using protoregistry.GlobalTypes.FindMessageByName
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// or constructing a dynamic MessageType using dynamicpb.NewMessageType.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// • A Message is a reflective view over a concrete message instance.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Generated messages implement ProtoMessage, which can convert to a Message.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Just as how Go's reflect.Value is a reflective view over a Go value,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// a Message is a reflective view over a concrete protobuf message instance.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// Using Go reflection as an analogy, the ProtoReflect method is similar to
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// calling reflect.ValueOf, and the Message.Interface method is similar to
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// calling reflect.Value.Interface.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	      ┌── TypeDescriptor() ──┐    ┌───── Descriptor() ─────┐
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	      │                      V    │                        V
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	╔═══════════════╗  ╔═════════════════════════╗  ╔═════════════════════╗
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	║ ExtensionType ║  ║ ExtensionTypeDescriptor ║  ║ ExtensionDescriptor ║
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	╚═══════════════╝  ╚═════════════════════════╝  ╚═════════════════════╝
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	      Λ                      │   │ Λ                      │ Λ
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	      └─────── Type() ───────┘   │ └─── may implement ────┘ │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	                                 │                          │
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//	                                 └────── implements ────────┘
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// • An ExtensionType describes a concrete Go implementation of an extension.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// It has an ExtensionTypeDescriptor and can convert to/from
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// abstract Values and Go values.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// • An ExtensionTypeDescriptor is an ExtensionDescriptor
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// which also has an ExtensionType.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// • An ExtensionDescriptor describes an abstract protobuf extension field and
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:5
// may not always be an ExtensionTypeDescriptor.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:131
package protoreflect

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:131
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:131
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:131
)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:131
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:131
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:131
)

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/internal/pragma"
)

type doNotImplement pragma.DoNotImplement

// ProtoMessage is the top-level interface that all proto messages implement.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:143
// This is declared in the protoreflect package to avoid a cyclic dependency;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:143
// use the proto.Message type instead, which aliases this type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:146
type ProtoMessage interface{ ProtoReflect() Message }

// Syntax is the language version of the proto file.
type Syntax syntax

type syntax int8	// keep exact type opaque as the int type may change

const (
	Proto2	Syntax	= 2
	Proto3	Syntax	= 3
)

// IsValid reports whether the syntax is valid.
func (s Syntax) IsValid() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:159
	_go_fuzz_dep_.CoverTab[48500]++
													switch s {
	case Proto2, Proto3:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:161
		_go_fuzz_dep_.CoverTab[48501]++
														return true
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:162
		// _ = "end of CoverTab[48501]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:163
		_go_fuzz_dep_.CoverTab[48502]++
														return false
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:164
		// _ = "end of CoverTab[48502]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:165
	// _ = "end of CoverTab[48500]"
}

// String returns s as a proto source identifier (e.g., "proto2").
func (s Syntax) String() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:169
	_go_fuzz_dep_.CoverTab[48503]++
													switch s {
	case Proto2:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:171
		_go_fuzz_dep_.CoverTab[48504]++
														return "proto2"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:172
		// _ = "end of CoverTab[48504]"
	case Proto3:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:173
		_go_fuzz_dep_.CoverTab[48505]++
														return "proto3"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:174
		// _ = "end of CoverTab[48505]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:175
		_go_fuzz_dep_.CoverTab[48506]++
														return fmt.Sprintf("<unknown:%d>", s)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:176
		// _ = "end of CoverTab[48506]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:177
	// _ = "end of CoverTab[48503]"
}

// GoString returns s as a Go source identifier (e.g., "Proto2").
func (s Syntax) GoString() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:181
	_go_fuzz_dep_.CoverTab[48507]++
													switch s {
	case Proto2:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:183
		_go_fuzz_dep_.CoverTab[48508]++
														return "Proto2"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:184
		// _ = "end of CoverTab[48508]"
	case Proto3:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:185
		_go_fuzz_dep_.CoverTab[48509]++
														return "Proto3"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:186
		// _ = "end of CoverTab[48509]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:187
		_go_fuzz_dep_.CoverTab[48510]++
														return fmt.Sprintf("Syntax(%d)", s)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:188
		// _ = "end of CoverTab[48510]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:189
	// _ = "end of CoverTab[48507]"
}

// Cardinality determines whether a field is optional, required, or repeated.
type Cardinality cardinality

type cardinality int8	// keep exact type opaque as the int type may change

// Constants as defined by the google.protobuf.Cardinality enumeration.
const (
	Optional	Cardinality	= 1	// appears zero or one times
	Required	Cardinality	= 2	// appears exactly one time; invalid with Proto3
	Repeated	Cardinality	= 3	// appears zero or more times
)

// IsValid reports whether the cardinality is valid.
func (c Cardinality) IsValid() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:205
	_go_fuzz_dep_.CoverTab[48511]++
													switch c {
	case Optional, Required, Repeated:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:207
		_go_fuzz_dep_.CoverTab[48512]++
														return true
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:208
		// _ = "end of CoverTab[48512]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:209
		_go_fuzz_dep_.CoverTab[48513]++
														return false
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:210
		// _ = "end of CoverTab[48513]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:211
	// _ = "end of CoverTab[48511]"
}

// String returns c as a proto source identifier (e.g., "optional").
func (c Cardinality) String() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:215
	_go_fuzz_dep_.CoverTab[48514]++
													switch c {
	case Optional:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:217
		_go_fuzz_dep_.CoverTab[48515]++
														return "optional"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:218
		// _ = "end of CoverTab[48515]"
	case Required:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:219
		_go_fuzz_dep_.CoverTab[48516]++
														return "required"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:220
		// _ = "end of CoverTab[48516]"
	case Repeated:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:221
		_go_fuzz_dep_.CoverTab[48517]++
														return "repeated"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:222
		// _ = "end of CoverTab[48517]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:223
		_go_fuzz_dep_.CoverTab[48518]++
														return fmt.Sprintf("<unknown:%d>", c)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:224
		// _ = "end of CoverTab[48518]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:225
	// _ = "end of CoverTab[48514]"
}

// GoString returns c as a Go source identifier (e.g., "Optional").
func (c Cardinality) GoString() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:229
	_go_fuzz_dep_.CoverTab[48519]++
													switch c {
	case Optional:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:231
		_go_fuzz_dep_.CoverTab[48520]++
														return "Optional"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:232
		// _ = "end of CoverTab[48520]"
	case Required:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:233
		_go_fuzz_dep_.CoverTab[48521]++
														return "Required"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:234
		// _ = "end of CoverTab[48521]"
	case Repeated:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:235
		_go_fuzz_dep_.CoverTab[48522]++
														return "Repeated"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:236
		// _ = "end of CoverTab[48522]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:237
		_go_fuzz_dep_.CoverTab[48523]++
														return fmt.Sprintf("Cardinality(%d)", c)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:238
		// _ = "end of CoverTab[48523]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:239
	// _ = "end of CoverTab[48519]"
}

// Kind indicates the basic proto kind of a field.
type Kind kind

type kind int8	// keep exact type opaque as the int type may change

// Constants as defined by the google.protobuf.Field.Kind enumeration.
const (
	BoolKind	Kind	= 8
	EnumKind	Kind	= 14
	Int32Kind	Kind	= 5
	Sint32Kind	Kind	= 17
	Uint32Kind	Kind	= 13
	Int64Kind	Kind	= 3
	Sint64Kind	Kind	= 18
	Uint64Kind	Kind	= 4
	Sfixed32Kind	Kind	= 15
	Fixed32Kind	Kind	= 7
	FloatKind	Kind	= 2
	Sfixed64Kind	Kind	= 16
	Fixed64Kind	Kind	= 6
	DoubleKind	Kind	= 1
	StringKind	Kind	= 9
	BytesKind	Kind	= 12
	MessageKind	Kind	= 11
	GroupKind	Kind	= 10
)

// IsValid reports whether the kind is valid.
func (k Kind) IsValid() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:270
	_go_fuzz_dep_.CoverTab[48524]++
													switch k {
	case BoolKind, EnumKind,
		Int32Kind, Sint32Kind, Uint32Kind,
		Int64Kind, Sint64Kind, Uint64Kind,
		Sfixed32Kind, Fixed32Kind, FloatKind,
		Sfixed64Kind, Fixed64Kind, DoubleKind,
		StringKind, BytesKind, MessageKind, GroupKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:277
		_go_fuzz_dep_.CoverTab[48525]++
														return true
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:278
		// _ = "end of CoverTab[48525]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:279
		_go_fuzz_dep_.CoverTab[48526]++
														return false
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:280
		// _ = "end of CoverTab[48526]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:281
	// _ = "end of CoverTab[48524]"
}

// String returns k as a proto source identifier (e.g., "bool").
func (k Kind) String() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:285
	_go_fuzz_dep_.CoverTab[48527]++
													switch k {
	case BoolKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:287
		_go_fuzz_dep_.CoverTab[48528]++
														return "bool"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:288
		// _ = "end of CoverTab[48528]"
	case EnumKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:289
		_go_fuzz_dep_.CoverTab[48529]++
														return "enum"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:290
		// _ = "end of CoverTab[48529]"
	case Int32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:291
		_go_fuzz_dep_.CoverTab[48530]++
														return "int32"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:292
		// _ = "end of CoverTab[48530]"
	case Sint32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:293
		_go_fuzz_dep_.CoverTab[48531]++
														return "sint32"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:294
		// _ = "end of CoverTab[48531]"
	case Uint32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:295
		_go_fuzz_dep_.CoverTab[48532]++
														return "uint32"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:296
		// _ = "end of CoverTab[48532]"
	case Int64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:297
		_go_fuzz_dep_.CoverTab[48533]++
														return "int64"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:298
		// _ = "end of CoverTab[48533]"
	case Sint64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:299
		_go_fuzz_dep_.CoverTab[48534]++
														return "sint64"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:300
		// _ = "end of CoverTab[48534]"
	case Uint64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:301
		_go_fuzz_dep_.CoverTab[48535]++
														return "uint64"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:302
		// _ = "end of CoverTab[48535]"
	case Sfixed32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:303
		_go_fuzz_dep_.CoverTab[48536]++
														return "sfixed32"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:304
		// _ = "end of CoverTab[48536]"
	case Fixed32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:305
		_go_fuzz_dep_.CoverTab[48537]++
														return "fixed32"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:306
		// _ = "end of CoverTab[48537]"
	case FloatKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:307
		_go_fuzz_dep_.CoverTab[48538]++
														return "float"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:308
		// _ = "end of CoverTab[48538]"
	case Sfixed64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:309
		_go_fuzz_dep_.CoverTab[48539]++
														return "sfixed64"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:310
		// _ = "end of CoverTab[48539]"
	case Fixed64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:311
		_go_fuzz_dep_.CoverTab[48540]++
														return "fixed64"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:312
		// _ = "end of CoverTab[48540]"
	case DoubleKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:313
		_go_fuzz_dep_.CoverTab[48541]++
														return "double"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:314
		// _ = "end of CoverTab[48541]"
	case StringKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:315
		_go_fuzz_dep_.CoverTab[48542]++
														return "string"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:316
		// _ = "end of CoverTab[48542]"
	case BytesKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:317
		_go_fuzz_dep_.CoverTab[48543]++
														return "bytes"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:318
		// _ = "end of CoverTab[48543]"
	case MessageKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:319
		_go_fuzz_dep_.CoverTab[48544]++
														return "message"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:320
		// _ = "end of CoverTab[48544]"
	case GroupKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:321
		_go_fuzz_dep_.CoverTab[48545]++
														return "group"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:322
		// _ = "end of CoverTab[48545]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:323
		_go_fuzz_dep_.CoverTab[48546]++
														return fmt.Sprintf("<unknown:%d>", k)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:324
		// _ = "end of CoverTab[48546]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:325
	// _ = "end of CoverTab[48527]"
}

// GoString returns k as a Go source identifier (e.g., "BoolKind").
func (k Kind) GoString() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:329
	_go_fuzz_dep_.CoverTab[48547]++
													switch k {
	case BoolKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:331
		_go_fuzz_dep_.CoverTab[48548]++
														return "BoolKind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:332
		// _ = "end of CoverTab[48548]"
	case EnumKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:333
		_go_fuzz_dep_.CoverTab[48549]++
														return "EnumKind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:334
		// _ = "end of CoverTab[48549]"
	case Int32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:335
		_go_fuzz_dep_.CoverTab[48550]++
														return "Int32Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:336
		// _ = "end of CoverTab[48550]"
	case Sint32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:337
		_go_fuzz_dep_.CoverTab[48551]++
														return "Sint32Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:338
		// _ = "end of CoverTab[48551]"
	case Uint32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:339
		_go_fuzz_dep_.CoverTab[48552]++
														return "Uint32Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:340
		// _ = "end of CoverTab[48552]"
	case Int64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:341
		_go_fuzz_dep_.CoverTab[48553]++
														return "Int64Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:342
		// _ = "end of CoverTab[48553]"
	case Sint64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:343
		_go_fuzz_dep_.CoverTab[48554]++
														return "Sint64Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:344
		// _ = "end of CoverTab[48554]"
	case Uint64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:345
		_go_fuzz_dep_.CoverTab[48555]++
														return "Uint64Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:346
		// _ = "end of CoverTab[48555]"
	case Sfixed32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:347
		_go_fuzz_dep_.CoverTab[48556]++
														return "Sfixed32Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:348
		// _ = "end of CoverTab[48556]"
	case Fixed32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:349
		_go_fuzz_dep_.CoverTab[48557]++
														return "Fixed32Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:350
		// _ = "end of CoverTab[48557]"
	case FloatKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:351
		_go_fuzz_dep_.CoverTab[48558]++
														return "FloatKind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:352
		// _ = "end of CoverTab[48558]"
	case Sfixed64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:353
		_go_fuzz_dep_.CoverTab[48559]++
														return "Sfixed64Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:354
		// _ = "end of CoverTab[48559]"
	case Fixed64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:355
		_go_fuzz_dep_.CoverTab[48560]++
														return "Fixed64Kind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:356
		// _ = "end of CoverTab[48560]"
	case DoubleKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:357
		_go_fuzz_dep_.CoverTab[48561]++
														return "DoubleKind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:358
		// _ = "end of CoverTab[48561]"
	case StringKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:359
		_go_fuzz_dep_.CoverTab[48562]++
														return "StringKind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:360
		// _ = "end of CoverTab[48562]"
	case BytesKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:361
		_go_fuzz_dep_.CoverTab[48563]++
														return "BytesKind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:362
		// _ = "end of CoverTab[48563]"
	case MessageKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:363
		_go_fuzz_dep_.CoverTab[48564]++
														return "MessageKind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:364
		// _ = "end of CoverTab[48564]"
	case GroupKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:365
		_go_fuzz_dep_.CoverTab[48565]++
														return "GroupKind"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:366
		// _ = "end of CoverTab[48565]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:367
		_go_fuzz_dep_.CoverTab[48566]++
														return fmt.Sprintf("Kind(%d)", k)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:368
		// _ = "end of CoverTab[48566]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:369
	// _ = "end of CoverTab[48547]"
}

// FieldNumber is the field number in a message.
type FieldNumber = protowire.Number

// FieldNumbers represent a list of field numbers.
type FieldNumbers interface {
	// Len reports the number of fields in the list.
	Len() int
	// Get returns the ith field number. It panics if out of bounds.
	Get(i int) FieldNumber
	// Has reports whether n is within the list of fields.
	Has(n FieldNumber) bool

	doNotImplement
}

// FieldRanges represent a list of field number ranges.
type FieldRanges interface {
	// Len reports the number of ranges in the list.
	Len() int
	// Get returns the ith range. It panics if out of bounds.
	Get(i int) [2]FieldNumber	// start inclusive; end exclusive
	// Has reports whether n is within any of the ranges.
	Has(n FieldNumber) bool

	doNotImplement
}

// EnumNumber is the numeric value for an enum.
type EnumNumber int32

// EnumRanges represent a list of enum number ranges.
type EnumRanges interface {
	// Len reports the number of ranges in the list.
	Len() int
	// Get returns the ith range. It panics if out of bounds.
	Get(i int) [2]EnumNumber	// start inclusive; end inclusive
	// Has reports whether n is within any of the ranges.
	Has(n EnumNumber) bool

	doNotImplement
}

// Name is the short name for a proto declaration. This is not the name
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:414
// as used in Go source code, which might not be identical to the proto name.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:416
type Name string	// e.g., "Kind"

// IsValid reports whether s is a syntactically valid name.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:418
// An empty name is invalid.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:420
func (s Name) IsValid() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:420
	_go_fuzz_dep_.CoverTab[48567]++
													return consumeIdent(string(s)) == len(s)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:421
	// _ = "end of CoverTab[48567]"
}

// Names represent a list of names.
type Names interface {
	// Len reports the number of names in the list.
	Len() int
	// Get returns the ith name. It panics if out of bounds.
	Get(i int) Name
	// Has reports whether s matches any names in the list.
	Has(s Name) bool

	doNotImplement
}

// FullName is a qualified name that uniquely identifies a proto declaration.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:436
// A qualified name is the concatenation of the proto package along with the
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:436
// fully-declared name (i.e., name of parent preceding the name of the child),
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:436
// with a '.' delimiter placed between each Name.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:436
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:436
// This should not have any leading or trailing dots.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:442
type FullName string	// e.g., "google.protobuf.Field.Kind"

// IsValid reports whether s is a syntactically valid full name.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:444
// An empty full name is invalid.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:446
func (s FullName) IsValid() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:446
	_go_fuzz_dep_.CoverTab[48568]++
													i := consumeIdent(string(s))
													if i < 0 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:448
		_go_fuzz_dep_.CoverTab[48571]++
														return false
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:449
		// _ = "end of CoverTab[48571]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:450
		_go_fuzz_dep_.CoverTab[48572]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:450
		// _ = "end of CoverTab[48572]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:450
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:450
	// _ = "end of CoverTab[48568]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:450
	_go_fuzz_dep_.CoverTab[48569]++
													for len(s) > i {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:451
		_go_fuzz_dep_.CoverTab[48573]++
														if s[i] != '.' {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:452
			_go_fuzz_dep_.CoverTab[48576]++
															return false
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:453
			// _ = "end of CoverTab[48576]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:454
			_go_fuzz_dep_.CoverTab[48577]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:454
			// _ = "end of CoverTab[48577]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:454
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:454
		// _ = "end of CoverTab[48573]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:454
		_go_fuzz_dep_.CoverTab[48574]++
														i++
														n := consumeIdent(string(s[i:]))
														if n < 0 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:457
			_go_fuzz_dep_.CoverTab[48578]++
															return false
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:458
			// _ = "end of CoverTab[48578]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:459
			_go_fuzz_dep_.CoverTab[48579]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:459
			// _ = "end of CoverTab[48579]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:459
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:459
		// _ = "end of CoverTab[48574]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:459
		_go_fuzz_dep_.CoverTab[48575]++
														i += n
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:460
		// _ = "end of CoverTab[48575]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:461
	// _ = "end of CoverTab[48569]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:461
	_go_fuzz_dep_.CoverTab[48570]++
													return true
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:462
	// _ = "end of CoverTab[48570]"
}

func consumeIdent(s string) (i int) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:465
	_go_fuzz_dep_.CoverTab[48580]++
													if len(s) == 0 || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:466
		_go_fuzz_dep_.CoverTab[48583]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:466
		return !isLetter(s[i])
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:466
		// _ = "end of CoverTab[48583]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:466
	}() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:466
		_go_fuzz_dep_.CoverTab[48584]++
														return -1
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:467
		// _ = "end of CoverTab[48584]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:468
		_go_fuzz_dep_.CoverTab[48585]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:468
		// _ = "end of CoverTab[48585]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:468
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:468
	// _ = "end of CoverTab[48580]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:468
	_go_fuzz_dep_.CoverTab[48581]++
													i++
													for len(s) > i && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:470
		_go_fuzz_dep_.CoverTab[48586]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:470
		return isLetterDigit(s[i])
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:470
		// _ = "end of CoverTab[48586]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:470
	}() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:470
		_go_fuzz_dep_.CoverTab[48587]++
														i++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:471
		// _ = "end of CoverTab[48587]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:472
	// _ = "end of CoverTab[48581]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:472
	_go_fuzz_dep_.CoverTab[48582]++
													return i
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:473
	// _ = "end of CoverTab[48582]"
}
func isLetter(c byte) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:475
	_go_fuzz_dep_.CoverTab[48588]++
													return c == '_' || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
		_go_fuzz_dep_.CoverTab[48589]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
		return ('a' <= c && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
			_go_fuzz_dep_.CoverTab[48590]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
			return c <= 'z'
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
			// _ = "end of CoverTab[48590]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
		}())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
		// _ = "end of CoverTab[48589]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
	}() || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
		_go_fuzz_dep_.CoverTab[48591]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
		return ('A' <= c && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
			_go_fuzz_dep_.CoverTab[48592]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
			return c <= 'Z'
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
			// _ = "end of CoverTab[48592]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
		}())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
		// _ = "end of CoverTab[48591]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:476
	// _ = "end of CoverTab[48588]"
}
func isLetterDigit(c byte) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:478
	_go_fuzz_dep_.CoverTab[48593]++
													return isLetter(c) || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:479
		_go_fuzz_dep_.CoverTab[48594]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:479
		return ('0' <= c && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:479
			_go_fuzz_dep_.CoverTab[48595]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:479
			return c <= '9'
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:479
			// _ = "end of CoverTab[48595]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:479
		}())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:479
		// _ = "end of CoverTab[48594]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:479
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:479
	// _ = "end of CoverTab[48593]"
}

// Name returns the short name, which is the last identifier segment.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:482
// A single segment FullName is the Name itself.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:484
func (n FullName) Name() Name {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:484
	_go_fuzz_dep_.CoverTab[48596]++
													if i := strings.LastIndexByte(string(n), '.'); i >= 0 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:485
		_go_fuzz_dep_.CoverTab[48598]++
														return Name(n[i+1:])
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:486
		// _ = "end of CoverTab[48598]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:487
		_go_fuzz_dep_.CoverTab[48599]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:487
		// _ = "end of CoverTab[48599]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:487
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:487
	// _ = "end of CoverTab[48596]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:487
	_go_fuzz_dep_.CoverTab[48597]++
													return Name(n)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:488
	// _ = "end of CoverTab[48597]"
}

// Parent returns the full name with the trailing identifier removed.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:491
// A single segment FullName has no parent.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:493
func (n FullName) Parent() FullName {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:493
	_go_fuzz_dep_.CoverTab[48600]++
													if i := strings.LastIndexByte(string(n), '.'); i >= 0 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:494
		_go_fuzz_dep_.CoverTab[48602]++
														return n[:i]
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:495
		// _ = "end of CoverTab[48602]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:496
		_go_fuzz_dep_.CoverTab[48603]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:496
		// _ = "end of CoverTab[48603]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:496
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:496
	// _ = "end of CoverTab[48600]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:496
	_go_fuzz_dep_.CoverTab[48601]++
													return ""
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:497
	// _ = "end of CoverTab[48601]"
}

// Append returns the qualified name appended with the provided short name.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:500
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:500
// Invariant: n == n.Parent().Append(n.Name()) // assuming n is valid
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:503
func (n FullName) Append(s Name) FullName {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:503
	_go_fuzz_dep_.CoverTab[48604]++
													if n == "" {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:504
		_go_fuzz_dep_.CoverTab[48606]++
														return FullName(s)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:505
		// _ = "end of CoverTab[48606]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:506
		_go_fuzz_dep_.CoverTab[48607]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:506
		// _ = "end of CoverTab[48607]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:506
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:506
	// _ = "end of CoverTab[48604]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:506
	_go_fuzz_dep_.CoverTab[48605]++
													return n + "." + FullName(s)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:507
	// _ = "end of CoverTab[48605]"
}

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:508
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoreflect/proto.go:508
var _ = _go_fuzz_dep_.CoverTab
