{
 "title": "DBUF Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ace_cluster", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Interface: TX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dbuf_interface_tx_ok_total", "legendFormat": "Ok Total" },
    { "expr": "dbuf_interface_tx_drop_total", "legendFormat": "Drop Total" }
   ]
  },
  {
   "title": "Interface: RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dbuf_interface_rx_ok_total", "legendFormat": "Ok Total" },
    { "expr": "dbuf_interface_rx_drop_total", "legendFormat": "Drop Total" }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dbuf_queue_dropped_total", "legendFormat": "Dropped Total" },
    {
     "expr": "dbuf_queue_full_discarded_total",
     "legendFormat": "Discarded Total"
    },
    { "expr": "dbuf_queue_released_total", "legendFormat": "Release Total" }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"dbuf-stats\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "go_goroutines{service=\"dbuf-stats\"}",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"dbuf-stats\"}[1m])",
     "legendFormat": "go_memstats_alloc_bytes_total"
    },
    {
     "expr": "go_memstats_alloc_bytes{service=\"dbuf-stats\"}",
     "legendFormat": "go_memstats_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{service=\"dbuf-stats\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{service=\"dbuf-stats\"}",
     "legendFormat": "go_memstats_heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"dbuf-stats\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{service=\"dbuf-stats\"}",
     "legendFormat": "go_memstats_heap_released_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{service=\"dbuf-stats\"}",
     "legendFormat": "go_memstats_heap_sys_bytes"
    }
   ]
  }
 ]
}