{
 "title": "Aether Connected Edge",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Pronto ACEs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 }, "options": { "content": "# Cornell University\n" } },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} - 3, 0) * 100)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"}), 0)) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} - 3, 0) - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"}), 0))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum(clamp_min((aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"} * -1) - 1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-cornell1-prd\"}, 0))",
     "legendFormat": "Test down"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.tunnel_name}}",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "production-ace-cornell1-*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": {
    "content": "# ONF\n### Menlo Park\n##### Raspberry Pi test"
   }
  },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} - 3, 0) * 100)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"}), 0)) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} - 3, 0) - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"}), 0))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum(clamp_min((aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"} * -1) - 1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo-rasp-pi\"}, 0))",
     "legendFormat": "Test down"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{ metric.label.tunnel_name }}",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "production-ace-menlo*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 }, "options": { "content": "# ONF\n### Tucson" } },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-tucson\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-tucson\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} - 3, 0) * 100)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-tucson\"}), 0)) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-tucson\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} - 3, 0) - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-tucson\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-tucson\"}), 0))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-tucson\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum(clamp_min((aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-tucson\"} * -1) - 1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-tucson\"}, 0))",
     "legendFormat": "Test down"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{ metric.label.tunnel_name }}",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "production-ace-tucson*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 }, "options": { "content": "# Princeton University\n" } },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} - 3, 0) * 100)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"}), 0)) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} - 3, 0) - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"}), 0))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum(clamp_min((aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"} * -1) - 1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-princeton1-prd\"}, 0))",
     "legendFormat": "Test down"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{ metric.label.tunnel_name }}",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "production-ace-princeton*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": {
    "content": "# Stanford University\n### EE Lab"
   }
  },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} - 3, 0) * 100)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"}), 0)) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} - 3, 0) - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"}), 0))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum(clamp_min((aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"} * -1) - 1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford1-prd\"}, 0))",
     "legendFormat": "Test down"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{ metric.label.tunnel_name }}",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "production-ace-stanford1*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "options": {
    "content": "# Stanford University\n### AA Lab"
   }
  },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} - 3, 0) * 100)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"}), 0)) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} - 3, 0) - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"}), 0))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum(clamp_min((aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"} * -1) - 1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-stanford2-prd\"}, 0))",
     "legendFormat": "Test down"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{ metric.label.tunnel_name }}",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "production-ace-stanford2*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  { "title": "Aether ACEs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 }, "options": { "content": "# Intel Corp" } },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-intel\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-intel\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-intel\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-intel\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-intel\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-intel\"} - 3, 0) * 100)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-intel\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-intel\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-intel\"}), 0)) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-intel\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-intel\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-intel\"} - 3, 0) - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-intel\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-intel\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-intel\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-intel\"}), 0))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-intel\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum(clamp_min((aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-intel\"} * -1) - 1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-intel\"}, 0))",
     "legendFormat": "Test down"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{ metric.label.tunnel_name }}",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "production-ace-intel*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 }, "options": { "content": "# NCTU" } },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-nctu\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-nctu\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} - 3, 0) * 100)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-nctu\"}), 0)) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-nctu\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} - 3, 0) - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-nctu\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-nctu\"}), 0))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-nctu\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum(clamp_min((aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-nctu\"} * -1) - 1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-nctu\"}, 0))",
     "legendFormat": "Test down"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{ metric.label.tunnel_name }}",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "production-ace-nctu*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "SD-CORE Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active subscribers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(spgw_number_of_ue_attached{cp_mode=\"spgw\",state=\"active\",level=\"subscribers\",job=\"spgwc\"})",
       "legendFormat": "SPGW"
      },
      {
       "expr": "sum(mme_number_of_ue_attached{endpoint=\"metrics3081\",level=\"subscribers\",sub_state=\"Active\"})",
       "legendFormat": "MME"
      }
     ]
    },
    {
     "title": "Current Subscriber Info",
     "type": "table",
     "gridPos": { "h": 15, "w": 9, "x": 4, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(subscribers_info{imsi=~\".+\"}[$__range])) by (imsi, mobile_ip)"
      }
     ]
    },
    {
     "title": "SPGW Procedurees Per Second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 11, "x": 13, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"success\",mme_addr=\"\",proc_type=\"\"}[5m])) by (procedure)",
       "legendFormat": "Success: {{procedure}}"
      },
      {
       "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"success\",mme_addr=\"\",proc_type=\"INITIAL_ATTACH\"}[5m])) by (proc_type)",
       "legendFormat": "Success: {{proc_type}}"
      },
      {
       "expr": "-1 * sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"failure\",mme_addr=\"\",proc_type=\"\"}[5m])) by (procedure)",
       "legendFormat": "Failure: {{procedure}}"
      }
     ]
    },
    {
     "title": "MME Procedures Per Second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 11, "x": 13, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(number_of_procedures{endpoint=\"metrics3081\",mme_app=\"procedure\",proc_result=\"success\"}[5m])) by (procedure)",
       "legendFormat": "Success: {{procedure}}"
      },
      {
       "expr": "-1 * sum(rate(number_of_procedures{endpoint=\"metrics3081\",mme_app=\"procedure\",proc_result=\"failure\"}[5m])) by (procedure)",
       "legendFormat": "Failure: {{procedure}}"
      }
     ]
    },
    {
     "title": "eNodeB Status",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mme_number_of_enb_attached{enb_state=\"Active\", enbname=~\".+\"}) by (enbname,enbid)",
       "legendFormat": "{{ enbname }}:{{ enbid }}"
      }
     ]
    },
    {
     "title": "HSS Messages Per Second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 11, "x": 13, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(number_of_messages_sent{endpoint=\"metrics3081\",interface=\"s6a\"}[5m])) by (msg_type)",
       "legendFormat": "{{msg_type}}"
      },
      {
       "expr": "sum(rate(number_of_messages_received{endpoint=\"metrics3081\",interface=\"s6a\"}[5m])) by (msg_type)",
       "legendFormat": "{{msg_type}}"
      }
     ]
    }
   ]
  }
 ]
}