{
 "title": "Aether Connected Edge",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Edge Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "# ONF\n### Menlo Park\n##### Staging"
   }
  },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} - 3, 0) * 100)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}), 0)) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} - 3, 0) - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"})",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}), 0))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum(clamp_min((aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} * -1) - 1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}, 0))",
     "legendFormat": "Test down"
    }
   ]
  },
  { "title": "Signal Quality (Beta)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": {
    "content": "# ONF\n### Menlo Park\n##### Staging"
   }
  },
  {
   "title": "RSRQ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aetheredge_signal_quality_rsrq{endpoint=\"metrics80\",name=\"ace-menlo\"} * 0.5 - 20 - (100 * aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"})",
     "legendFormat": "RSRQ"
    }
   ]
  },
  {
   "title": "RSRQ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "aetheredge_signal_quality_rsrq{endpoint=\"metrics80\",name=\"$edge\"} * 0.5 - 20",
     "legendFormat": "rsrq"
    },
    {
     "expr": "-100 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"$edge\"}) + 1",
     "legendFormat": "maint"
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aetheredge_signal_quality_rsrp{endpoint=\"metrics80\",name=\"ace-menlo\"} - 141 - (200 * aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"})",
     "legendFormat": "RSRP"
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "aetheredge_signal_quality_rsrp{endpoint=\"metrics80\",name=\"ace-menlo\"} - 141",
     "legendFormat": "rsrp"
    },
    {
     "expr": "-200 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"$edge\"}) + 1",
     "legendFormat": "maint"
    }
   ]
  },
  { "title": "Speed Test Results (Beta)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "options": {
    "content": "# ONF\n### Menlo Park\n##### Staging"
   }
  },
  {
   "type": "graph",
   "description": "**Ping Latency Tests Over Time**\n- Ping DNS Avg: Pings to 8.8.8.8, average latency of 10 iterations\n- Ping Iperf Server Avg: Pings the iperf server on the cluster, average latency of 10 iterations",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(aetheredge_ping_dns_test_avg{endpoint=\"metrics80\",name=\"ace-menlo\"}) > 0 and (sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} * -1 + 1)) - sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) <= 0",
     "legendFormat": "Ping DNS Avg"
    },
    {
     "expr": "sum(aetheredge_ping_iperf_server_test_avg{endpoint=\"metrics80\",name=\"ace-menlo\"}) > 0 and (sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} * -1 + 1)) - sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) <= 0",
     "legendFormat": "Ping Iperf Server Avg"
    },
    {
     "expr": "(sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"}) * -1 + 1) - sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) - (sum(5*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}))",
     "legendFormat": "Edge Down"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"})",
     "legendFormat": "Edge Maintenance"
    }
   ]
  },
  {
   "type": "graph",
   "description": "**Iperf Downlink and Uplink Tests Over Time**\n- Max Downlink Speed: 115 Mbps\n- Max Uplink Speed: 10 Mbps\n\nEach result is taken from the iperf json output, test runs for 10 seconds.",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "sum(aetheredge_iperf_cluster_downlink_test{endpoint=\"metrics80\",name=\"ace-menlo\"}) > 0 and (sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} * -1 + 1)) - sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) <= 0",
     "legendFormat": "Downlink Speed"
    },
    {
     "expr": "sum(aetheredge_iperf_cluster_uplink_test{endpoint=\"metrics80\",name=\"ace-menlo\"} > 0) and (sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"} * -1 + 1)) - sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) <= 0",
     "legendFormat": "Uplink Speed"
    },
    { "expr": "10", "legendFormat": "Max UL (10 Mbps)" },
    { "expr": "115", "legendFormat": "Max DL (115 Mbps)" },
    {
     "expr": "(sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"ace-menlo\"}) * -1 + 1) - sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) - (sum(5*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}))",
     "legendFormat": "Edge Down"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"})",
     "legendFormat": "Edge Maintenance"
    }
   ]
  },
  { "title": "SD-CORE Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "eNodeB Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mme_number_of_enb_attached{enb_state=\"Active\", enbname=~\".+\"}) by (enbname)",
     "legendFormat": "{{ enbname }}"
    }
   ]
  },
  {
   "title": "Current Subscriber Info",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(subscribers_info{imsi=~\".+\"}[$__range])) by (imsi, mobile_ip)"
    }
   ]
  },
  {
   "title": "SPGW Procedurees Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"success\",mme_addr=\"\",proc_type=\"\"}[5m])) by (procedure)",
     "legendFormat": "Success: {{procedure}}"
    },
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"success\",mme_addr=\"\",proc_type=\"INITIAL_ATTACH\"}[5m])) by (proc_type)",
     "legendFormat": "Success: {{proc_type}}"
    },
    {
     "expr": "-1 * sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"failure\",mme_addr=\"\",proc_type=\"\"}[5m])) by (procedure)",
     "legendFormat": "Failure: {{procedure}}"
    }
   ]
  },
  {
   "title": "MME Procedures Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{endpoint=\"metrics3081\",mme_app=\"procedure\",proc_result=\"success\"}[5m])) by (procedure)",
     "legendFormat": "Success: {{procedure}}"
    },
    {
     "expr": "-1 * sum(rate(number_of_procedures{endpoint=\"metrics3081\",mme_app=\"procedure\",proc_result=\"failure\"}[5m])) by (procedure)",
     "legendFormat": "Failure: {{procedure}}"
    }
   ]
  },
  {
   "title": "Active subscribers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spgw_number_of_ue_attached{cp_mode=\"spgw\",state=\"active\",level=\"subscribers\",job=\"spgwc-metrics\"})",
     "legendFormat": "SPGW"
    },
    {
     "expr": "sum(mme_number_of_ue_attached{endpoint=\"metrics3081\",level=\"subscribers\",sub_state=\"Active\"})",
     "legendFormat": "MME"
    }
   ]
  },
  {
   "title": "HSS Messages Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_messages_sent{endpoint=\"metrics3081\",interface=\"s6a\"}[5m])) by (msg_type)",
     "legendFormat": "{{msg_type}}"
    },
    {
     "expr": "sum(rate(number_of_messages_received{endpoint=\"metrics3081\",interface=\"s6a\"}[5m])) by (msg_type)",
     "legendFormat": "{{msg_type}}"
    }
   ]
  }
 ]
}