{
 "title": "SD-CORE Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Active subscribers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spgw_number_of_ue_attached{cp_mode=\"spgw\",state=\"active\",level=\"subscribers\",job=\"spgwc\"})",
     "legendFormat": "SPGW"
    },
    {
     "expr": "sum(mme_number_of_ue_attached{endpoint=\"metrics3081\",level=\"subscribers\",sub_state=\"Active\"})",
     "legendFormat": "MME"
    }
   ]
  },
  {
   "title": "SPGW Procedures: Successes Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc\",result=\"success\",mme_addr=\"\",proc_type=\"\"}[5m])) by (procedure)",
     "legendFormat": "{{procedure}}"
    },
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc\",result=\"success\",mme_addr=\"\",proc_type=\"INITIAL_ATTACH\"}[5m])) by (proc_type)",
     "legendFormat": "{{proc_type}}"
    }
   ]
  },
  {
   "title": "SPGW Procedures: Failures Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc\",result=\"failure\",mme_addr=\"\",proc_type=\"\"}[5m])) by (procedure)",
     "legendFormat": "{{procedure}}"
    },
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc\",result=\"failure\",mme_addr=\"\",proc_type=\"INITIAL_ATTACH\"}[5m])) by (proc_type)",
     "legendFormat": "{{proc_type}}"
    }
   ]
  },
  {
   "title": "MME Procedures: Successes Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{endpoint=\"metrics3081\",mme_app=\"procedure\",proc_result=\"success\"}[5m])) by (procedure)",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "MME Procedures: Failures Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{endpoint=\"metrics3081\",mme_app=\"procedure\",proc_result=\"failure\"}[5m])) by (procedure)",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Ready replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"omec\"}",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "HSS Messages Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_messages_sent{endpoint=\"metrics3081\",interface=\"s6a\"}[5m])) by (msg_type)",
     "legendFormat": "{{msg_type}}"
    },
    {
     "expr": "sum(rate(number_of_messages_received{endpoint=\"metrics3081\",interface=\"s6a\"}[5m])) by (msg_type)",
     "legendFormat": "{{msg_type}}"
    }
   ]
  }
 ]
}