{
 "title": "SD-CORE Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "SPGW: Active Subscribers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(spgw_number_of_ue_attached{spgw_num_ue=\"subscribers\",cp_mode=\"spgw\",level=\"subscribers\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "SPGW: Active Subscribers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spgw_number_of_ue_attached{spgw_num_ue=\"subscribers\",cp_mode=\"spgw\",level=\"subscribers\",state=\"active\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "SPGW: Initial Attach Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_procedures{gw=\"procedures\",cp_mode=\"spgw\",proc_type=\"INITIAL_ATTACH\",result=\"success\"})/2",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_procedures{gw=\"procedures\",cp_mode=\"spgw\",proc_type=\"INITIAL_ATTACH\",result=\"failure\"})/2",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "SPGW: UE / MME / HSS Detach Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_procedures{gw=\"procedures\",cp_mode=\"spgw\",procedure=\"MME_INIT_DETACH\", result=\"success\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_procedures{gw=\"procedures\",cp_mode=\"spgw\",procedure=\"MME_INIT_DETACH\", result=\"failure\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "SPGW: S1 Release Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_procedures{gw=\"procedures\",cp_mode=\"spgw\",procedure=\"S1_RELEASE\",result=\"success\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_procedures{gw=\"procedures\",cp_mode=\"spgw\",procedure=\"S1_RELEASE\",result=\"failure\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "SPGW: Service Request Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_procedures{gw=\"procedures\",cp_mode=\"spgw\",procedure=\"SERVICE_REQUEST_PROC\",result=\"success\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_procedures{gw=\"procedures\",cp_mode=\"spgw\",procedure=\"SERVICE_REQUEST_PROC\",result=\"failure\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "HSS: Authentication Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_messages_sent{direction=\"outgoing\",interface=\"s6a\",msg_type=\"auth_info_answer\",result=\"success\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_messages_sent{direction=\"outgoing\",interface=\"s6a\",msg_type=\"auth_info_answer\",result=\"failure\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "HSS: Update Location Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_messages_sent{direction=\"outgoing\",interface=\"s6a\",msg_type=\"update_location_answer\",result=\"success\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_messages_sent{direction=\"outgoing\",interface=\"s6a\",msg_type=\"update_location_answer\",result=\"failure\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "MME: Subscribers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(mme_number_of_ue_attached{mme=\"num_ue\",level=\"subscribers\",sub_state=\"Active\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(mme_number_of_ue_attached{mme=\"num_ue\",level=\"subscribers\",sub_state=\"Idle\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "MME: Subscribers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mme_number_of_ue_attached{mme=\"num_ue\",level=\"subscribers\",sub_state=\"Active\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(mme_number_of_ue_attached{mme=\"num_ue\",level=\"subscribers\",sub_state=\"Idle\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "MME: Attach Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"success\",procedure=\"ATTACH_PROC\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"failure\",procedure=\"ATTACH_PROC\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "MME: Detach Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(number_of_procedures{mme_app=\"procedure\",detach_type=\"ue_init\",procedure=\"DETACH_PROC\",proc_result=\"success\"}[2m])*60",
     "legendFormat": "{{ result }}"
    },
    {
     "expr": "rate(number_of_procedures{mme_app=\"procedure\",detach_type=\"ue_init\",procedure=\"DETACH_PROC\",proc_result=\"failure\"}[2m])*60",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "MME: S1 Release Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"success\",procedure=\"S1_RELEASE_PROC\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"failure\",procedure=\"S1_RELEASE_PROC\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "MME: Service Request Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"success\",procedure=\"SERVICE_REQUEST_PROC\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"failure\",procedure=\"SERVICE_REQUEST_PROC\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "MME: TAU Procs Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"success\",procedure=\"TAU_PROC\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"failure\",procedure=\"TAU_PROC\"})",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "MME: eNB Handover Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"success\",procedure=\"S1_ENB_HANDOVER_PROC\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(number_of_procedures{mme_app=\"procedure\",proc_result=\"failure\",procedure=\"S1_ENB_HANDOVER_PROC\"})",
     "legendFormat": "failure"
    }
   ]
  }
 ]
}