{
 "title": "TOST Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "es_datasource", "label": "Log_Datasource", "query": "elasticsearch" },
   { "name": "es_namespace", "query": "tost" },
   {
    "name": "es_pod",
    "label": "Pod",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.pod_name.keyword\",\"query\":\"kubernetes.namespace_name.keyword:$es_namespace\"}"
   },
   {
    "name": "es_container",
    "label": "Container",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.container_name.keyword\",\"query\":\"kubernetes.namespace_name.keyword:$es_namespace AND kubernetes.pod_name.keyword:$es_pod\"}\t"
   },
   {
    "name": "es_loglevel",
    "label": "Log Level",
    "query": "{\"find\": \"terms\", \"field\": \"logLevel.keyword\",\"query\":\"kubernetes.namespace_name.keyword:$es_namespace AND kubernetes.pod_name.keyword:$es_pod AND kubernetes.container_name.keyword:$es_container\"}\t"
   }
  ]
 },
 "panels": [
  {
   "title": "ONOS Cluster Ready",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "onos_telegraf_ready", "legendFormat": "Ready" }
   ]
  },
  {
   "title": "Topology Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "onos_telegraf_active_links", "legendFormat": "Active Links" },
    { "expr": "onos_telegraf_devices", "legendFormat": "Devies" },
    {
     "expr": "onos_telegraf_enable_device_ports",
     "legendFormat": "Enabled Device Ports"
    }
   ]
  },
  {
   "title": "Stratum Couter (octect)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "stratum_counters_in_octets", "legendFormat": "in-{{ source }}:{{ name }} " },
    { "expr": "stratum_counters_out_octets", "legendFormat": "out-{{ source }}:{{ name }}" }
   ]
  },
  {
   "title": "Stratum Counter (errors)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "stratum_counters_in_errors", "legendFormat": "in-{{ source }}:{{ name }} " },
    { "expr": "stratum_counters_out_errors", "legendFormat": "out-{{ source }}:{{ name }}" }
   ]
  },
  {
   "title": "Ping Response Time (MS)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ping_average_response_ms{namespace=\"tost\"}) by (url)",
     "legendFormat": "average_{{ url }} "
    },
    {
     "expr": "sum(ping_maximum_response_ms{namespace=\"tost\"}) by (url)",
     "legendFormat": "max_{{ url }} "
    },
    {
     "expr": "sum(ping_minimum_response_ms{namespace=\"tost\"}) by (url)",
     "legendFormat": "min_{{ url }} "
    }
   ]
  },
  {
   "title": "Ping packet loss (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(ping_percent_packet_loss{namespace=\"tost\"}) by (url)",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Namespace $es_namespace: Log Messages Per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "repeat": "pod",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.namespace_name.keyword:$es_namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod $es_pod: Log Messages per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod_name.keyword:$es_pod AND kubernetes.namespace_name.keyword:$es_namespace AND (logLevel.keyword:$es_loglevel)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$es_pod Logs ($es_container)",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.container_name.keyword:$es_container AND kubernetes.pod_name.keyword:$es_pod AND kubernetes.namespace_name.keyword:$es_namespace AND (logLevel.keyword:$es_loglevel)",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}