{
 "title": "VPN Tunnels",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tunnel",
    "label": "Tunnel",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "tunnel" },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "$tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Established",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Tunnel established",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Bytes received",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Bytes sent",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packet drops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Outgoing",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Incoming",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "$tunnel"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}