// Protocol Buffers - Google's data interchange format
// Copyright 2008 Google Inc.  All rights reserved.
// https://developers.google.com/protocol-buffers/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/protobuf/any.proto

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// Package anypb contains generated types for google/protobuf/any.proto.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// The Any message is a dynamic representation of any other message value.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// It is functionally a tuple of the full name of the remote message type and
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// the serialized bytes of the remote message value.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// # Constructing an Any
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// An Any message containing another message value is constructed using New:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	any, err := anypb.New(m)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	if err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		... // handle error
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	... // make use of any
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// # Unmarshaling an Any
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// With a populated Any message, the underlying message can be serialized into
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// a remote concrete message value in a few ways.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// If the exact concrete type is known, then a new (or pre-existing) instance
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// of that message can be passed to the UnmarshalTo method:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	m := new(foopb.MyMessage)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	if err := any.UnmarshalTo(m); err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		... // handle error
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	... // make use of m
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// If the exact concrete type is not known, then the UnmarshalNew method can be
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// used to unmarshal the contents into a new instance of the remote message type:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	m, err := any.UnmarshalNew()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	if err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		... // handle error
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	... // make use of m
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// UnmarshalNew uses the global type registry to resolve the message type and
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// construct a new instance of that message to unmarshal into. In order for a
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// message type to appear in the global registry, the Go type representing that
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// protobuf message type must be linked into the Go binary. For messages
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// generated by protoc-gen-go, this is achieved through an import of the
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// generated Go package representing a .proto file.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// A common pattern with UnmarshalNew is to use a type switch with the resulting
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// proto.Message value:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	switch m := m.(type) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	case *foopb.MyMessage:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		... // make use of m as a *foopb.MyMessage
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	case *barpb.OtherMessage:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		... // make use of m as a *barpb.OtherMessage
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	case *bazpb.SomeMessage:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		... // make use of m as a *bazpb.SomeMessage
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// This pattern ensures that the generated packages containing the message types
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// listed in the case clauses are linked into the Go binary and therefore also
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// registered in the global registry.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// # Type checking an Any
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// In order to type check whether an Any message represents some other message,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// then use the MessageIs method:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	if any.MessageIs((*foopb.MyMessage)(nil)) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		... // make use of any, knowing that it contains a foopb.MyMessage
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// The MessageIs method can also be used with an allocated instance of the target
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
// message type if the intention is to unmarshal into it if the type matches:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	m := new(foopb.MyMessage)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	if any.MessageIs(m) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		if err := any.UnmarshalTo(m); err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//			... // handle error
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//		... // make use of m
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:34
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:119
package anypb

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:119
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:119
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:119
)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:119
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:119
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:119
)

import (
	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoregistry "google.golang.org/protobuf/reflect/protoregistry"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	strings "strings"
	sync "sync"
)

// `Any` contains an arbitrary serialized protocol buffer message along with a
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// URL that describes the type of the serialized message.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// Protobuf library provides support to pack/unpack Any values in the form
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// of utility functions or additional generated methods of the Any type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// Example 1: Pack and unpack a message in C++.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	Foo foo = ...;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	Any any;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	any.PackFrom(foo);
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	...
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	if (any.UnpackTo(&foo)) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	  ...
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// Example 2: Pack and unpack a message in Java.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   Foo foo = ...;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   Any any = Any.pack(foo);
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   ...
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   if (any.is(Foo.class)) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	     foo = any.unpack(Foo.class);
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   }
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	Example 3: Pack and unpack a message in Python.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   foo = Foo(...)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   any = Any()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   any.Pack(foo)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   ...
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	   if any.Is(Foo.DESCRIPTOR):
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	     any.Unpack(foo)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	     ...
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	Example 4: Pack and unpack a message in Go
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	    foo := &pb.Foo{...}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	    any, err := anypb.New(foo)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	    if err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	      ...
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	    }
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	    ...
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	    foo := &pb.Foo{}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	    if err := any.UnmarshalTo(foo); err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	      ...
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	    }
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// The pack methods provided by protobuf library will by default use
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// 'type.googleapis.com/full.type.name' as the type URL and the unpack
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// methods only use the fully qualified type name after the last '/'
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// in the type URL, for example "foo.bar.com/x/y.z" will yield type
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// name "y.z".
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// JSON
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// ====
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// The JSON representation of an `Any` value uses the regular
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// representation of the deserialized, embedded message, with an
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// additional field `@type` which contains the type URL. Example:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	package google.profile;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	message Person {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	  string first_name = 1;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	  string last_name = 2;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	{
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	  "@type": "type.googleapis.com/google.profile.Person",
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	  "firstName": <string>,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	  "lastName": <string>
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// If the embedded message type is well-known and has a custom JSON
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// representation, that representation will be embedded adding a field
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// `value` which holds the custom JSON in addition to the `@type`
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
// field. Example (for message [google.protobuf.Duration][]):
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	{
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	  "@type": "type.googleapis.com/google.protobuf.Duration",
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	  "value": "1.212s"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:131
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:214
type Any struct {
	state		protoimpl.MessageState
	sizeCache	protoimpl.SizeCache
	unknownFields	protoimpl.UnknownFields

	// A URL/resource name that uniquely identifies the type of the serialized
	// protocol buffer message. This string must contain at least
	// one "/" character. The last segment of the URL's path must represent
	// the fully qualified name of the type (as in
	// `path/google.protobuf.Duration`). The name should be in a canonical form
	// (e.g., leading "." is not accepted).
	//
	// In practice, teams usually precompile into the binary all types that they
	// expect it to use in the context of Any. However, for URLs which use the
	// scheme `http`, `https`, or no scheme, one can optionally set up a type
	// server that maps type URLs to message definitions as follows:
	//
	// * If no scheme is provided, `https` is assumed.
	// * An HTTP GET on the URL must yield a [google.protobuf.Type][]
	//   value in binary format, or produce an error.
	// * Applications are allowed to cache lookup results based on the
	//   URL, or have them precompiled into a binary to avoid any
	//   lookup. Therefore, binary compatibility needs to be preserved
	//   on changes to types. (Use versioned type names to manage
	//   breaking changes.)
	//
	// Note: this functionality is not currently available in the official
	// protobuf release, and it is not used for type URLs beginning with
	// type.googleapis.com.
	//
	// Schemes other than `http`, `https` (or the empty scheme) might be
	// used with implementation specific semantics.
	//
	TypeUrl	string	`protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	// Must be a valid serialized protocol buffer of the above specified type.
	Value	[]byte	`protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

// New marshals src into a new Any instance.
func New(src proto.Message) (*Any, error) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:253
	_go_fuzz_dep_.CoverTab[67791]++
													dst := new(Any)
													if err := dst.MarshalFrom(src); err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:255
		_go_fuzz_dep_.CoverTab[67793]++
														return nil, err
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:256
		// _ = "end of CoverTab[67793]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:257
		_go_fuzz_dep_.CoverTab[67794]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:257
		// _ = "end of CoverTab[67794]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:257
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:257
	// _ = "end of CoverTab[67791]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:257
	_go_fuzz_dep_.CoverTab[67792]++
													return dst, nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:258
	// _ = "end of CoverTab[67792]"
}

// MarshalFrom marshals src into dst as the underlying message
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:261
// using the provided marshal options.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:261
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:261
// If no options are specified, call dst.MarshalFrom instead.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:265
func MarshalFrom(dst *Any, src proto.Message, opts proto.MarshalOptions) error {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:265
	_go_fuzz_dep_.CoverTab[67795]++
													const urlPrefix = "type.googleapis.com/"
													if src == nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:267
		_go_fuzz_dep_.CoverTab[67798]++
														return protoimpl.X.NewError("invalid nil source message")
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:268
		// _ = "end of CoverTab[67798]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:269
		_go_fuzz_dep_.CoverTab[67799]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:269
		// _ = "end of CoverTab[67799]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:269
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:269
	// _ = "end of CoverTab[67795]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:269
	_go_fuzz_dep_.CoverTab[67796]++
													b, err := opts.Marshal(src)
													if err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:271
		_go_fuzz_dep_.CoverTab[67800]++
														return err
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:272
		// _ = "end of CoverTab[67800]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:273
		_go_fuzz_dep_.CoverTab[67801]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:273
		// _ = "end of CoverTab[67801]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:273
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:273
	// _ = "end of CoverTab[67796]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:273
	_go_fuzz_dep_.CoverTab[67797]++
													dst.TypeUrl = urlPrefix + string(src.ProtoReflect().Descriptor().FullName())
													dst.Value = b
													return nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:276
	// _ = "end of CoverTab[67797]"
}

// UnmarshalTo unmarshals the underlying message from src into dst
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:279
// using the provided unmarshal options.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:279
// It reports an error if dst is not of the right message type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:279
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:279
// If no options are specified, call src.UnmarshalTo instead.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:284
func UnmarshalTo(src *Any, dst proto.Message, opts proto.UnmarshalOptions) error {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:284
	_go_fuzz_dep_.CoverTab[67802]++
													if src == nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:285
		_go_fuzz_dep_.CoverTab[67805]++
														return protoimpl.X.NewError("invalid nil source message")
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:286
		// _ = "end of CoverTab[67805]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:287
		_go_fuzz_dep_.CoverTab[67806]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:287
		// _ = "end of CoverTab[67806]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:287
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:287
	// _ = "end of CoverTab[67802]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:287
	_go_fuzz_dep_.CoverTab[67803]++
													if !src.MessageIs(dst) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:288
		_go_fuzz_dep_.CoverTab[67807]++
														got := dst.ProtoReflect().Descriptor().FullName()
														want := src.MessageName()
														return protoimpl.X.NewError("mismatched message type: got %q, want %q", got, want)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:291
		// _ = "end of CoverTab[67807]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:292
		_go_fuzz_dep_.CoverTab[67808]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:292
		// _ = "end of CoverTab[67808]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:292
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:292
	// _ = "end of CoverTab[67803]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:292
	_go_fuzz_dep_.CoverTab[67804]++
													return opts.Unmarshal(src.GetValue(), dst)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:293
	// _ = "end of CoverTab[67804]"
}

// UnmarshalNew unmarshals the underlying message from src into dst,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:296
// which is newly created message using a type resolved from the type URL.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:296
// The message type is resolved according to opt.Resolver,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:296
// which should implement protoregistry.MessageTypeResolver.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:296
// It reports an error if the underlying message type could not be resolved.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:296
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:296
// If no options are specified, call src.UnmarshalNew instead.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:303
func UnmarshalNew(src *Any, opts proto.UnmarshalOptions) (dst proto.Message, err error) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:303
	_go_fuzz_dep_.CoverTab[67809]++
													if src.GetTypeUrl() == "" {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:304
		_go_fuzz_dep_.CoverTab[67814]++
														return nil, protoimpl.X.NewError("invalid empty type URL")
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:305
		// _ = "end of CoverTab[67814]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:306
		_go_fuzz_dep_.CoverTab[67815]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:306
		// _ = "end of CoverTab[67815]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:306
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:306
	// _ = "end of CoverTab[67809]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:306
	_go_fuzz_dep_.CoverTab[67810]++
													if opts.Resolver == nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:307
		_go_fuzz_dep_.CoverTab[67816]++
														opts.Resolver = protoregistry.GlobalTypes
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:308
		// _ = "end of CoverTab[67816]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:309
		_go_fuzz_dep_.CoverTab[67817]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:309
		// _ = "end of CoverTab[67817]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:309
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:309
	// _ = "end of CoverTab[67810]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:309
	_go_fuzz_dep_.CoverTab[67811]++
													r, ok := opts.Resolver.(protoregistry.MessageTypeResolver)
													if !ok {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:311
		_go_fuzz_dep_.CoverTab[67818]++
														return nil, protoregistry.NotFound
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:312
		// _ = "end of CoverTab[67818]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:313
		_go_fuzz_dep_.CoverTab[67819]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:313
		// _ = "end of CoverTab[67819]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:313
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:313
	// _ = "end of CoverTab[67811]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:313
	_go_fuzz_dep_.CoverTab[67812]++
													mt, err := r.FindMessageByURL(src.GetTypeUrl())
													if err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:315
		_go_fuzz_dep_.CoverTab[67820]++
														if err == protoregistry.NotFound {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:316
			_go_fuzz_dep_.CoverTab[67822]++
															return nil, err
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:317
			// _ = "end of CoverTab[67822]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:318
			_go_fuzz_dep_.CoverTab[67823]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:318
			// _ = "end of CoverTab[67823]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:318
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:318
		// _ = "end of CoverTab[67820]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:318
		_go_fuzz_dep_.CoverTab[67821]++
														return nil, protoimpl.X.NewError("could not resolve %q: %v", src.GetTypeUrl(), err)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:319
		// _ = "end of CoverTab[67821]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:320
		_go_fuzz_dep_.CoverTab[67824]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:320
		// _ = "end of CoverTab[67824]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:320
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:320
	// _ = "end of CoverTab[67812]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:320
	_go_fuzz_dep_.CoverTab[67813]++
													dst = mt.New().Interface()
													return dst, opts.Unmarshal(src.GetValue(), dst)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:322
	// _ = "end of CoverTab[67813]"
}

// MessageIs reports whether the underlying message is of the same type as m.
func (x *Any) MessageIs(m proto.Message) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:326
	_go_fuzz_dep_.CoverTab[67825]++
													if m == nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:327
		_go_fuzz_dep_.CoverTab[67828]++
														return false
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:328
		// _ = "end of CoverTab[67828]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:329
		_go_fuzz_dep_.CoverTab[67829]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:329
		// _ = "end of CoverTab[67829]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:329
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:329
	// _ = "end of CoverTab[67825]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:329
	_go_fuzz_dep_.CoverTab[67826]++
													url := x.GetTypeUrl()
													name := string(m.ProtoReflect().Descriptor().FullName())
													if !strings.HasSuffix(url, name) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:332
		_go_fuzz_dep_.CoverTab[67830]++
														return false
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:333
		// _ = "end of CoverTab[67830]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:334
		_go_fuzz_dep_.CoverTab[67831]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:334
		// _ = "end of CoverTab[67831]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:334
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:334
	// _ = "end of CoverTab[67826]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:334
	_go_fuzz_dep_.CoverTab[67827]++
													return len(url) == len(name) || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:335
		_go_fuzz_dep_.CoverTab[67832]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:335
		return url[len(url)-len(name)-1] == '/'
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:335
		// _ = "end of CoverTab[67832]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:335
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:335
	// _ = "end of CoverTab[67827]"
}

// MessageName reports the full name of the underlying message,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:338
// returning an empty string if invalid.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:340
func (x *Any) MessageName() protoreflect.FullName {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:340
	_go_fuzz_dep_.CoverTab[67833]++
													url := x.GetTypeUrl()
													name := protoreflect.FullName(url)
													if i := strings.LastIndexByte(url, '/'); i >= 0 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:343
		_go_fuzz_dep_.CoverTab[67836]++
														name = name[i+len("/"):]
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:344
		// _ = "end of CoverTab[67836]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:345
		_go_fuzz_dep_.CoverTab[67837]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:345
		// _ = "end of CoverTab[67837]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:345
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:345
	// _ = "end of CoverTab[67833]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:345
	_go_fuzz_dep_.CoverTab[67834]++
													if !name.IsValid() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:346
		_go_fuzz_dep_.CoverTab[67838]++
														return ""
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:347
		// _ = "end of CoverTab[67838]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:348
		_go_fuzz_dep_.CoverTab[67839]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:348
		// _ = "end of CoverTab[67839]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:348
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:348
	// _ = "end of CoverTab[67834]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:348
	_go_fuzz_dep_.CoverTab[67835]++
													return name
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:349
	// _ = "end of CoverTab[67835]"
}

// MarshalFrom marshals m into x as the underlying message.
func (x *Any) MarshalFrom(m proto.Message) error {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:353
	_go_fuzz_dep_.CoverTab[67840]++
													return MarshalFrom(x, m, proto.MarshalOptions{})
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:354
	// _ = "end of CoverTab[67840]"
}

// UnmarshalTo unmarshals the contents of the underlying message of x into m.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:357
// It resets m before performing the unmarshal operation.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:357
// It reports an error if m is not of the right message type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:360
func (x *Any) UnmarshalTo(m proto.Message) error {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:360
	_go_fuzz_dep_.CoverTab[67841]++
													return UnmarshalTo(x, m, proto.UnmarshalOptions{})
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:361
	// _ = "end of CoverTab[67841]"
}

// UnmarshalNew unmarshals the contents of the underlying message of x into
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:364
// a newly allocated message of the specified type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:364
// It reports an error if the underlying message type could not be resolved.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:367
func (x *Any) UnmarshalNew() (proto.Message, error) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:367
	_go_fuzz_dep_.CoverTab[67842]++
													return UnmarshalNew(x, proto.UnmarshalOptions{})
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:368
	// _ = "end of CoverTab[67842]"
}

func (x *Any) Reset() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:371
	_go_fuzz_dep_.CoverTab[67843]++
													*x = Any{}
													if protoimpl.UnsafeEnabled {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:373
		_go_fuzz_dep_.CoverTab[67844]++
														mi := &file_google_protobuf_any_proto_msgTypes[0]
														ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
														ms.StoreMessageInfo(mi)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:376
		// _ = "end of CoverTab[67844]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:377
		_go_fuzz_dep_.CoverTab[67845]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:377
		// _ = "end of CoverTab[67845]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:377
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:377
	// _ = "end of CoverTab[67843]"
}

func (x *Any) String() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:380
	_go_fuzz_dep_.CoverTab[67846]++
													return protoimpl.X.MessageStringOf(x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:381
	// _ = "end of CoverTab[67846]"
}

func (*Any) ProtoMessage()	{ _go_fuzz_dep_.CoverTab[67847]++; // _ = "end of CoverTab[67847]" }

func (x *Any) ProtoReflect() protoreflect.Message {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:386
	_go_fuzz_dep_.CoverTab[67848]++
													mi := &file_google_protobuf_any_proto_msgTypes[0]
													if protoimpl.UnsafeEnabled && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:388
		_go_fuzz_dep_.CoverTab[67850]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:388
		return x != nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:388
		// _ = "end of CoverTab[67850]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:388
	}() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:388
		_go_fuzz_dep_.CoverTab[67851]++
														ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
														if ms.LoadMessageInfo() == nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:390
			_go_fuzz_dep_.CoverTab[67853]++
															ms.StoreMessageInfo(mi)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:391
			// _ = "end of CoverTab[67853]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:392
			_go_fuzz_dep_.CoverTab[67854]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:392
			// _ = "end of CoverTab[67854]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:392
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:392
		// _ = "end of CoverTab[67851]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:392
		_go_fuzz_dep_.CoverTab[67852]++
														return ms
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:393
		// _ = "end of CoverTab[67852]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:394
		_go_fuzz_dep_.CoverTab[67855]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:394
		// _ = "end of CoverTab[67855]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:394
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:394
	// _ = "end of CoverTab[67848]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:394
	_go_fuzz_dep_.CoverTab[67849]++
													return mi.MessageOf(x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:395
	// _ = "end of CoverTab[67849]"
}

// Deprecated: Use Any.ProtoReflect.Descriptor instead.
func (*Any) Descriptor() ([]byte, []int) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:399
	_go_fuzz_dep_.CoverTab[67856]++
													return file_google_protobuf_any_proto_rawDescGZIP(), []int{0}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:400
	// _ = "end of CoverTab[67856]"
}

func (x *Any) GetTypeUrl() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:403
	_go_fuzz_dep_.CoverTab[67857]++
													if x != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:404
		_go_fuzz_dep_.CoverTab[67859]++
														return x.TypeUrl
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:405
		// _ = "end of CoverTab[67859]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:406
		_go_fuzz_dep_.CoverTab[67860]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:406
		// _ = "end of CoverTab[67860]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:406
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:406
	// _ = "end of CoverTab[67857]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:406
	_go_fuzz_dep_.CoverTab[67858]++
													return ""
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:407
	// _ = "end of CoverTab[67858]"
}

func (x *Any) GetValue() []byte {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:410
	_go_fuzz_dep_.CoverTab[67861]++
													if x != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:411
		_go_fuzz_dep_.CoverTab[67863]++
														return x.Value
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:412
		// _ = "end of CoverTab[67863]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:413
		_go_fuzz_dep_.CoverTab[67864]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:413
		// _ = "end of CoverTab[67864]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:413
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:413
	// _ = "end of CoverTab[67861]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:413
	_go_fuzz_dep_.CoverTab[67862]++
													return nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:414
	// _ = "end of CoverTab[67862]"
}

var File_google_protobuf_any_proto protoreflect.FileDescriptor

var file_google_protobuf_any_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x36, 0x0a, 0x03,
	0x41, 0x6e, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x79, 0x70, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x76, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x08, 0x41, 0x6e, 0x79,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x2f,
	0x61, 0x6e, 0x79, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x47, 0x50, 0x42, 0xaa, 0x02, 0x1e, 0x47, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x57, 0x65,
	0x6c, 0x6c, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_protobuf_any_proto_rawDescOnce	sync.Once
	file_google_protobuf_any_proto_rawDescData	= file_google_protobuf_any_proto_rawDesc
)

func file_google_protobuf_any_proto_rawDescGZIP() []byte {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:442
	_go_fuzz_dep_.CoverTab[67865]++
													file_google_protobuf_any_proto_rawDescOnce.Do(func() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:443
		_go_fuzz_dep_.CoverTab[67867]++
														file_google_protobuf_any_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_protobuf_any_proto_rawDescData)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:444
		// _ = "end of CoverTab[67867]"
	})
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:445
	// _ = "end of CoverTab[67865]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:445
	_go_fuzz_dep_.CoverTab[67866]++
													return file_google_protobuf_any_proto_rawDescData
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:446
	// _ = "end of CoverTab[67866]"
}

var file_google_protobuf_any_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_protobuf_any_proto_goTypes = []interface{}{
	(*Any)(nil),
}
var file_google_protobuf_any_proto_depIdxs = []int32{
	0,
	0,
	0,
	0,
	0,
}

func init()	{ file_google_protobuf_any_proto_init() }
func file_google_protobuf_any_proto_init() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:462
	_go_fuzz_dep_.CoverTab[67868]++
													if File_google_protobuf_any_proto != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:463
		_go_fuzz_dep_.CoverTab[67871]++
														return
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:464
		// _ = "end of CoverTab[67871]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:465
		_go_fuzz_dep_.CoverTab[67872]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:465
		// _ = "end of CoverTab[67872]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:465
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:465
	// _ = "end of CoverTab[67868]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:465
	_go_fuzz_dep_.CoverTab[67869]++
													if !protoimpl.UnsafeEnabled {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:466
		_go_fuzz_dep_.CoverTab[67873]++
														file_google_protobuf_any_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:467
			_go_fuzz_dep_.CoverTab[67874]++
															switch v := v.(*Any); i {
			case 0:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:469
				_go_fuzz_dep_.CoverTab[67875]++
																return &v.state
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:470
				// _ = "end of CoverTab[67875]"
			case 1:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:471
				_go_fuzz_dep_.CoverTab[67876]++
																return &v.sizeCache
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:472
				// _ = "end of CoverTab[67876]"
			case 2:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:473
				_go_fuzz_dep_.CoverTab[67877]++
																return &v.unknownFields
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:474
				// _ = "end of CoverTab[67877]"
			default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:475
				_go_fuzz_dep_.CoverTab[67878]++
																return nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:476
				// _ = "end of CoverTab[67878]"
			}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:477
			// _ = "end of CoverTab[67874]"
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:478
		// _ = "end of CoverTab[67873]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:479
		_go_fuzz_dep_.CoverTab[67879]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:479
		// _ = "end of CoverTab[67879]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:479
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:479
	// _ = "end of CoverTab[67869]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:479
	_go_fuzz_dep_.CoverTab[67870]++
													type x struct{}
													out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath:	reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor:	file_google_protobuf_any_proto_rawDesc,
			NumEnums:	0,
			NumMessages:	1,
			NumExtensions:	0,
			NumServices:	0,
		},
		GoTypes:		file_google_protobuf_any_proto_goTypes,
		DependencyIndexes:	file_google_protobuf_any_proto_depIdxs,
		MessageInfos:		file_google_protobuf_any_proto_msgTypes,
	}.Build()
													File_google_protobuf_any_proto = out.File
													file_google_protobuf_any_proto_rawDesc = nil
													file_google_protobuf_any_proto_goTypes = nil
													file_google_protobuf_any_proto_depIdxs = nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:497
	// _ = "end of CoverTab[67870]"
}

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:498
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/anypb/any.pb.go:498
var _ = _go_fuzz_dep_.CoverTab
