// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

// Copyright 2021 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build go1.18
// +build go1.18

//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:10
package idna

//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:10
import (
//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:10
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:10
)
//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:10
import (
//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:10
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:10
)

// Transitional processing is disabled by default in Go 1.18.
//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:12
// https://golang.org/issue/47510
//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:14
const transitionalLookup = false

//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:14
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/golang.org/x/net@v0.10.0/idna/go118.go:14
var _ = _go_fuzz_dep_.CoverTab
