# Copyright 2021-present Open Networking Foundation
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ros-core
  labels:
{{ tuple "ros-core" . | include "ros-core.metadata_labels" | indent 4 }}
data:
  run_roscore.sh: |
{{ tuple "bin/_run_roscore.sh.tpl" . | include "ros-core.template" | indent 4 }}
  net_listener.py: |
{{ tuple "bin/_net_listener.py.tpl" . | include "ros-core.template" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ros-core-launch
  labels:
{{ tuple "ros-core-launch" . | include "ros-core.metadata_labels" | indent 4 }}
data:
{{- range $key, $value := .Values.config.rosCore.launchFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}