# Copyright 2021-present Open Networking Foundation
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcs
  labels:
{{ tuple "gcs" . | include "ros-core.metadata_labels" | indent 4 }}
data:
  run_gcs.sh: |
{{ tuple "bin/_run_gcs.sh.tpl" . | include "ros-core.template" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcs-launch
  labels:
{{ tuple "gcs-launch" . | include "ros-core.metadata_labels" | indent 4 }}
data:
{{- range $key, $value := .Values.config.gcs.launchFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcs-trajectory
  labels:
{{ tuple "gcs-trajectory" . | include "ros-core.metadata_labels" | indent 4 }}
data:
{{- range $key, $value := .Values.config.gcs.trajectoryFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}