// Protocol Buffers - Google's data interchange format
// Copyright 2008 Google Inc.  All rights reserved.
// https://developers.google.com/protocol-buffers/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/protobuf/timestamp.proto

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// Package timestamppb contains generated types for google/protobuf/timestamp.proto.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// The Timestamp message represents a timestamp,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// an instant in time since the Unix epoch (January 1st, 1970).
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// # Conversion to a Go Time
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// The AsTime method can be used to convert a Timestamp message to a
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// standard Go time.Time value in UTC:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//	t := ts.AsTime()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//	... // make use of t as a time.Time
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// Converting to a time.Time is a common operation so that the extensive
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// set of time-based operations provided by the time package can be leveraged.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// See https://golang.org/pkg/time for more information.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// The AsTime method performs the conversion on a best-effort basis. Timestamps
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// with denormal values (e.g., nanoseconds beyond 0 and 99999999, inclusive)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// are normalized during the conversion to a time.Time. To manually check for
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// invalid Timestamps per the documented limitations in timestamp.proto,
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// additionally call the CheckValid method:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//	if err := ts.CheckValid(); err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//		... // handle error
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// # Conversion from a Go Time
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// The timestamppb.New function can be used to construct a Timestamp message
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// from a standard Go time.Time value:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//	ts := timestamppb.New(t)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//	... // make use of ts as a *timestamppb.Timestamp
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
// In order to construct a Timestamp representing the current time, use Now:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//	ts := timestamppb.Now()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:34
//	... // make use of ts as a *timestamppb.Timestamp
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:76
package timestamppb

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:76
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:76
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:76
)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:76
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:76
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:76
)

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	time "time"
)

// A Timestamp represents a point in time independent of any time zone or local
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// calendar, encoded as a count of seconds and fractions of seconds at
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// nanosecond resolution. The count is relative to an epoch at UTC midnight on
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// January 1, 1970, in the proleptic Gregorian calendar which extends the
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// Gregorian calendar backwards to year one.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// All minutes are 60 seconds long. Leap seconds are "smeared" so that no leap
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// second table is needed for interpretation, using a [24-hour linear
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// smear](https://developers.google.com/time/smear).
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// restricting to that range, we ensure that we can convert to and from [RFC
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// 3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// # Examples
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// Example 1: Compute Timestamp from POSIX `time()`.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	Timestamp timestamp;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	timestamp.set_seconds(time(NULL));
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	timestamp.set_nanos(0);
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// Example 2: Compute Timestamp from POSIX `gettimeofday()`.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	struct timeval tv;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	gettimeofday(&tv, NULL);
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	Timestamp timestamp;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	timestamp.set_seconds(tv.tv_sec);
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	timestamp.set_nanos(tv.tv_usec * 1000);
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	FILETIME ft;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	GetSystemTimeAsFileTime(&ft);
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	// A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	// is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	Timestamp timestamp;
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	long millis = System.currentTimeMillis();
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	    .setNanos((int) ((millis % 1000) * 1000000)).build();
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// Example 5: Compute Timestamp from Java `Instant.now()`.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	Instant now = Instant.now();
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	Timestamp timestamp =
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	    Timestamp.newBuilder().setSeconds(now.getEpochSecond())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	        .setNanos(now.getNano()).build();
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// Example 6: Compute Timestamp from current time in Python.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	timestamp = Timestamp()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//	timestamp.GetCurrentTime()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// # JSON Mapping
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// In JSON format, the Timestamp type is encoded as a string in the
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// where {year} is always expressed using four digits while {month}, {day},
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// is required. A proto3 JSON serializer should always use UTC (as indicated by
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// "Z") when printing the Timestamp type and a proto3 JSON parser should be
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// able to accept both UTC and other timezones (as indicated by an offset).
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// 01:30 UTC on January 15, 2017.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// In JavaScript, one can convert a Date object to this format using the
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// standard
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// method. In Python, a standard `datetime.datetime` object can be converted
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// to this format using
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// the Joda Time's [`ISODateTimeFormat.dateTime()`](
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// http://www.joda.org/joda-time/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime%2D%2D
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:86
// ) to obtain a formatter capable of generating timestamps in this format.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:179
type Timestamp struct {
	state		protoimpl.MessageState
	sizeCache	protoimpl.SizeCache
	unknownFields	protoimpl.UnknownFields

	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds	int64	`protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos	int32	`protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
}

// Now constructs a new Timestamp from the current time.
func Now() *Timestamp {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:196
	_go_fuzz_dep_.CoverTab[67958]++
															return New(time.Now())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:197
	// _ = "end of CoverTab[67958]"
}

// New constructs a new Timestamp from the provided time.Time.
func New(t time.Time) *Timestamp {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:201
	_go_fuzz_dep_.CoverTab[67959]++
															return &Timestamp{Seconds: int64(t.Unix()), Nanos: int32(t.Nanosecond())}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:202
	// _ = "end of CoverTab[67959]"
}

// AsTime converts x to a time.Time.
func (x *Timestamp) AsTime() time.Time {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:206
	_go_fuzz_dep_.CoverTab[67960]++
															return time.Unix(int64(x.GetSeconds()), int64(x.GetNanos())).UTC()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:207
	// _ = "end of CoverTab[67960]"
}

// IsValid reports whether the timestamp is valid.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:210
// It is equivalent to CheckValid == nil.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:212
func (x *Timestamp) IsValid() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:212
	_go_fuzz_dep_.CoverTab[67961]++
															return x.check() == 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:213
	// _ = "end of CoverTab[67961]"
}

// CheckValid returns an error if the timestamp is invalid.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:216
// In particular, it checks whether the value represents a date that is
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:216
// in the range of 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:216
// An error is reported for a nil Timestamp.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:220
func (x *Timestamp) CheckValid() error {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:220
	_go_fuzz_dep_.CoverTab[67962]++
															switch x.check() {
	case invalidNil:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:222
		_go_fuzz_dep_.CoverTab[67963]++
																return protoimpl.X.NewError("invalid nil Timestamp")
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:223
		// _ = "end of CoverTab[67963]"
	case invalidUnderflow:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:224
		_go_fuzz_dep_.CoverTab[67964]++
																return protoimpl.X.NewError("timestamp (%v) before 0001-01-01", x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:225
		// _ = "end of CoverTab[67964]"
	case invalidOverflow:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:226
		_go_fuzz_dep_.CoverTab[67965]++
																return protoimpl.X.NewError("timestamp (%v) after 9999-12-31", x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:227
		// _ = "end of CoverTab[67965]"
	case invalidNanos:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:228
		_go_fuzz_dep_.CoverTab[67966]++
																return protoimpl.X.NewError("timestamp (%v) has out-of-range nanos", x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:229
		// _ = "end of CoverTab[67966]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:230
		_go_fuzz_dep_.CoverTab[67967]++
																return nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:231
		// _ = "end of CoverTab[67967]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:232
	// _ = "end of CoverTab[67962]"
}

const (
	_	= iota
	invalidNil
	invalidUnderflow
	invalidOverflow
	invalidNanos
)

func (x *Timestamp) check() uint {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:243
	_go_fuzz_dep_.CoverTab[67968]++
															const minTimestamp = -62135596800	// Seconds between 1970-01-01T00:00:00Z and 0001-01-01T00:00:00Z, inclusive
															const maxTimestamp = +253402300799	// Seconds between 1970-01-01T00:00:00Z and 9999-12-31T23:59:59Z, inclusive
															secs := x.GetSeconds()
															nanos := x.GetNanos()
															switch {
	case x == nil:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:249
		_go_fuzz_dep_.CoverTab[67969]++
																return invalidNil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:250
		// _ = "end of CoverTab[67969]"
	case secs < minTimestamp:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:251
		_go_fuzz_dep_.CoverTab[67970]++
																return invalidUnderflow
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:252
		// _ = "end of CoverTab[67970]"
	case secs > maxTimestamp:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:253
		_go_fuzz_dep_.CoverTab[67971]++
																return invalidOverflow
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:254
		// _ = "end of CoverTab[67971]"
	case nanos < 0 || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:255
		_go_fuzz_dep_.CoverTab[67974]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:255
		return nanos >= 1e9
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:255
		// _ = "end of CoverTab[67974]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:255
	}():
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:255
		_go_fuzz_dep_.CoverTab[67972]++
																return invalidNanos
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:256
		// _ = "end of CoverTab[67972]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:257
		_go_fuzz_dep_.CoverTab[67973]++
																return 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:258
		// _ = "end of CoverTab[67973]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:259
	// _ = "end of CoverTab[67968]"
}

func (x *Timestamp) Reset() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:262
	_go_fuzz_dep_.CoverTab[67975]++
															*x = Timestamp{}
															if protoimpl.UnsafeEnabled {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:264
		_go_fuzz_dep_.CoverTab[67976]++
																mi := &file_google_protobuf_timestamp_proto_msgTypes[0]
																ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
																ms.StoreMessageInfo(mi)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:267
		// _ = "end of CoverTab[67976]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:268
		_go_fuzz_dep_.CoverTab[67977]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:268
		// _ = "end of CoverTab[67977]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:268
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:268
	// _ = "end of CoverTab[67975]"
}

func (x *Timestamp) String() string {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:271
	_go_fuzz_dep_.CoverTab[67978]++
															return protoimpl.X.MessageStringOf(x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:272
	// _ = "end of CoverTab[67978]"
}

func (*Timestamp) ProtoMessage()	{ _go_fuzz_dep_.CoverTab[67979]++; // _ = "end of CoverTab[67979]" }

func (x *Timestamp) ProtoReflect() protoreflect.Message {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:277
	_go_fuzz_dep_.CoverTab[67980]++
															mi := &file_google_protobuf_timestamp_proto_msgTypes[0]
															if protoimpl.UnsafeEnabled && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:279
		_go_fuzz_dep_.CoverTab[67982]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:279
		return x != nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:279
		// _ = "end of CoverTab[67982]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:279
	}() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:279
		_go_fuzz_dep_.CoverTab[67983]++
																ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
																if ms.LoadMessageInfo() == nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:281
			_go_fuzz_dep_.CoverTab[67985]++
																	ms.StoreMessageInfo(mi)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:282
			// _ = "end of CoverTab[67985]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:283
			_go_fuzz_dep_.CoverTab[67986]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:283
			// _ = "end of CoverTab[67986]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:283
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:283
		// _ = "end of CoverTab[67983]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:283
		_go_fuzz_dep_.CoverTab[67984]++
																return ms
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:284
		// _ = "end of CoverTab[67984]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:285
		_go_fuzz_dep_.CoverTab[67987]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:285
		// _ = "end of CoverTab[67987]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:285
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:285
	// _ = "end of CoverTab[67980]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:285
	_go_fuzz_dep_.CoverTab[67981]++
															return mi.MessageOf(x)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:286
	// _ = "end of CoverTab[67981]"
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:290
	_go_fuzz_dep_.CoverTab[67988]++
															return file_google_protobuf_timestamp_proto_rawDescGZIP(), []int{0}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:291
	// _ = "end of CoverTab[67988]"
}

func (x *Timestamp) GetSeconds() int64 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:294
	_go_fuzz_dep_.CoverTab[67989]++
															if x != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:295
		_go_fuzz_dep_.CoverTab[67991]++
																return x.Seconds
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:296
		// _ = "end of CoverTab[67991]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:297
		_go_fuzz_dep_.CoverTab[67992]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:297
		// _ = "end of CoverTab[67992]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:297
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:297
	// _ = "end of CoverTab[67989]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:297
	_go_fuzz_dep_.CoverTab[67990]++
															return 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:298
	// _ = "end of CoverTab[67990]"
}

func (x *Timestamp) GetNanos() int32 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:301
	_go_fuzz_dep_.CoverTab[67993]++
															if x != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:302
		_go_fuzz_dep_.CoverTab[67995]++
																return x.Nanos
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:303
		// _ = "end of CoverTab[67995]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:304
		_go_fuzz_dep_.CoverTab[67996]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:304
		// _ = "end of CoverTab[67996]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:304
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:304
	// _ = "end of CoverTab[67993]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:304
	_go_fuzz_dep_.CoverTab[67994]++
															return 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:305
	// _ = "end of CoverTab[67994]"
}

var File_google_protobuf_timestamp_proto protoreflect.FileDescriptor

var file_google_protobuf_timestamp_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x3b, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6e,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x42,
	0x85, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x0e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x32, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x70, 0x62, 0xf8, 0x01, 0x01,
	0xa2, 0x02, 0x03, 0x47, 0x50, 0x42, 0xaa, 0x02, 0x1e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x57, 0x65, 0x6c, 0x6c, 0x4b, 0x6e, 0x6f,
	0x77, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_protobuf_timestamp_proto_rawDescOnce	sync.Once
	file_google_protobuf_timestamp_proto_rawDescData	= file_google_protobuf_timestamp_proto_rawDesc
)

func file_google_protobuf_timestamp_proto_rawDescGZIP() []byte {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:334
	_go_fuzz_dep_.CoverTab[67997]++
															file_google_protobuf_timestamp_proto_rawDescOnce.Do(func() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:335
		_go_fuzz_dep_.CoverTab[67999]++
																file_google_protobuf_timestamp_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_protobuf_timestamp_proto_rawDescData)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:336
		// _ = "end of CoverTab[67999]"
	})
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:337
	// _ = "end of CoverTab[67997]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:337
	_go_fuzz_dep_.CoverTab[67998]++
															return file_google_protobuf_timestamp_proto_rawDescData
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:338
	// _ = "end of CoverTab[67998]"
}

var file_google_protobuf_timestamp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_protobuf_timestamp_proto_goTypes = []interface{}{
	(*Timestamp)(nil),
}
var file_google_protobuf_timestamp_proto_depIdxs = []int32{
	0,
	0,
	0,
	0,
	0,
}

func init()	{ file_google_protobuf_timestamp_proto_init() }
func file_google_protobuf_timestamp_proto_init() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:354
	_go_fuzz_dep_.CoverTab[68000]++
															if File_google_protobuf_timestamp_proto != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:355
		_go_fuzz_dep_.CoverTab[68003]++
																return
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:356
		// _ = "end of CoverTab[68003]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:357
		_go_fuzz_dep_.CoverTab[68004]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:357
		// _ = "end of CoverTab[68004]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:357
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:357
	// _ = "end of CoverTab[68000]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:357
	_go_fuzz_dep_.CoverTab[68001]++
															if !protoimpl.UnsafeEnabled {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:358
		_go_fuzz_dep_.CoverTab[68005]++
																file_google_protobuf_timestamp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:359
			_go_fuzz_dep_.CoverTab[68006]++
																	switch v := v.(*Timestamp); i {
			case 0:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:361
				_go_fuzz_dep_.CoverTab[68007]++
																		return &v.state
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:362
				// _ = "end of CoverTab[68007]"
			case 1:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:363
				_go_fuzz_dep_.CoverTab[68008]++
																		return &v.sizeCache
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:364
				// _ = "end of CoverTab[68008]"
			case 2:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:365
				_go_fuzz_dep_.CoverTab[68009]++
																		return &v.unknownFields
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:366
				// _ = "end of CoverTab[68009]"
			default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:367
				_go_fuzz_dep_.CoverTab[68010]++
																		return nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:368
				// _ = "end of CoverTab[68010]"
			}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:369
			// _ = "end of CoverTab[68006]"
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:370
		// _ = "end of CoverTab[68005]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:371
		_go_fuzz_dep_.CoverTab[68011]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:371
		// _ = "end of CoverTab[68011]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:371
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:371
	// _ = "end of CoverTab[68001]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:371
	_go_fuzz_dep_.CoverTab[68002]++
															type x struct{}
															out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath:	reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor:	file_google_protobuf_timestamp_proto_rawDesc,
			NumEnums:	0,
			NumMessages:	1,
			NumExtensions:	0,
			NumServices:	0,
		},
		GoTypes:		file_google_protobuf_timestamp_proto_goTypes,
		DependencyIndexes:	file_google_protobuf_timestamp_proto_depIdxs,
		MessageInfos:		file_google_protobuf_timestamp_proto_msgTypes,
	}.Build()
															File_google_protobuf_timestamp_proto = out.File
															file_google_protobuf_timestamp_proto_rawDesc = nil
															file_google_protobuf_timestamp_proto_goTypes = nil
															file_google_protobuf_timestamp_proto_depIdxs = nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:389
	// _ = "end of CoverTab[68002]"
}

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:390
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/types/known/timestamppb/timestamp.pb.go:390
var _ = _go_fuzz_dep_.CoverTab
