/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_Coverage_Modification_Notification_H_
#define	_Coverage_Modification_Notification_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Coverage-Modification-List.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Coverage-Modification-Notification */
typedef struct Coverage_Modification_Notification {
	Coverage_Modification_List_t	 coverage_Modification_List;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Coverage_Modification_Notification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Coverage_Modification_Notification;
extern asn_SEQUENCE_specifics_t asn_SPC_Coverage_Modification_Notification_specs_1;
extern asn_TYPE_member_t asn_MBR_Coverage_Modification_Notification_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Coverage_Modification_Notification_H_ */
#include "asn_internal.h"
