/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_DU_RX_MT_TX_Extend_H_
#define	_DU_RX_MT_TX_Extend_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DU_RX_MT_TX_Extend {
	DU_RX_MT_TX_Extend_supported	= 0,
	DU_RX_MT_TX_Extend_not_supported	= 1,
	DU_RX_MT_TX_Extend_supported_and_FDM_required	= 2
	/*
	 * Enumeration is extensible
	 */
} e_DU_RX_MT_TX_Extend;

/* DU-RX-MT-TX-Extend */
typedef long	 DU_RX_MT_TX_Extend_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DU_RX_MT_TX_Extend_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DU_RX_MT_TX_Extend;
extern const asn_INTEGER_specifics_t asn_SPC_DU_RX_MT_TX_Extend_specs_1;
asn_struct_free_f DU_RX_MT_TX_Extend_free;
asn_struct_print_f DU_RX_MT_TX_Extend_print;
asn_constr_check_f DU_RX_MT_TX_Extend_constraint;
ber_type_decoder_f DU_RX_MT_TX_Extend_decode_ber;
der_type_encoder_f DU_RX_MT_TX_Extend_encode_der;
xer_type_decoder_f DU_RX_MT_TX_Extend_decode_xer;
xer_type_encoder_f DU_RX_MT_TX_Extend_encode_xer;
jer_type_encoder_f DU_RX_MT_TX_Extend_encode_jer;
oer_type_decoder_f DU_RX_MT_TX_Extend_decode_oer;
oer_type_encoder_f DU_RX_MT_TX_Extend_encode_oer;
per_type_decoder_f DU_RX_MT_TX_Extend_decode_uper;
per_type_encoder_f DU_RX_MT_TX_Extend_encode_uper;
per_type_decoder_f DU_RX_MT_TX_Extend_decode_aper;
per_type_encoder_f DU_RX_MT_TX_Extend_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DU_RX_MT_TX_Extend_H_ */
#include "asn_internal.h"
