/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_MBS_Flows_Mapped_To_MRB_Item_H_
#define	_MBS_Flows_Mapped_To_MRB_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "QoSFlowIdentifier.h"
#include "QoSFlowLevelQoSParameters.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* MBS-Flows-Mapped-To-MRB-Item */
typedef struct MBS_Flows_Mapped_To_MRB_Item {
	QoSFlowIdentifier_t	 mBS_QoSFlowIdentifier;
	QoSFlowLevelQoSParameters_t	 mbs_QoSFlowLevelQoSParameters;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBS_Flows_Mapped_To_MRB_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBS_Flows_Mapped_To_MRB_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_MBS_Flows_Mapped_To_MRB_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_MBS_Flows_Mapped_To_MRB_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MBS_Flows_Mapped_To_MRB_Item_H_ */
#include "asn_internal.h"
