/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_MBSMulticastF1UContextDescriptor_H_
#define	_MBSMulticastF1UContextDescriptor_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MulticastF1UContextReferenceF1.h"
#include "NativeEnumerated.h"
#include "MBS-Area-Session-ID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBSMulticastF1UContextDescriptor__mc_F1UCtxtusage {
	MBSMulticastF1UContextDescriptor__mc_F1UCtxtusage_ptm	= 0,
	MBSMulticastF1UContextDescriptor__mc_F1UCtxtusage_ptp	= 1,
	MBSMulticastF1UContextDescriptor__mc_F1UCtxtusage_ptp_retransmission	= 2,
	MBSMulticastF1UContextDescriptor__mc_F1UCtxtusage_ptp_forwarding	= 3
	/*
	 * Enumeration is extensible
	 */
} e_MBSMulticastF1UContextDescriptor__mc_F1UCtxtusage;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* MBSMulticastF1UContextDescriptor */
typedef struct MBSMulticastF1UContextDescriptor {
	MulticastF1UContextReferenceF1_t	 multicastF1UContextReferenceF1;
	long	 mc_F1UCtxtusage;
	MBS_Area_Session_ID_t	*mbsAreaSession;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBSMulticastF1UContextDescriptor_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_mc_F1UCtxtusage_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MBSMulticastF1UContextDescriptor;
extern asn_SEQUENCE_specifics_t asn_SPC_MBSMulticastF1UContextDescriptor_specs_1;
extern asn_TYPE_member_t asn_MBR_MBSMulticastF1UContextDescriptor_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _MBSMulticastF1UContextDescriptor_H_ */
#include "asn_internal.h"
