/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_NRPaging_eDRX_Cycle_Inactive_H_
#define	_NRPaging_eDRX_Cycle_Inactive_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPaging_eDRX_Cycle_Inactive {
	NRPaging_eDRX_Cycle_Inactive_hfquarter	= 0,
	NRPaging_eDRX_Cycle_Inactive_hfhalf	= 1,
	NRPaging_eDRX_Cycle_Inactive_hf1	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NRPaging_eDRX_Cycle_Inactive;

/* NRPaging-eDRX-Cycle-Inactive */
typedef long	 NRPaging_eDRX_Cycle_Inactive_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPaging_eDRX_Cycle_Inactive_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPaging_eDRX_Cycle_Inactive;
extern const asn_INTEGER_specifics_t asn_SPC_NRPaging_eDRX_Cycle_Inactive_specs_1;
asn_struct_free_f NRPaging_eDRX_Cycle_Inactive_free;
asn_struct_print_f NRPaging_eDRX_Cycle_Inactive_print;
asn_constr_check_f NRPaging_eDRX_Cycle_Inactive_constraint;
ber_type_decoder_f NRPaging_eDRX_Cycle_Inactive_decode_ber;
der_type_encoder_f NRPaging_eDRX_Cycle_Inactive_encode_der;
xer_type_decoder_f NRPaging_eDRX_Cycle_Inactive_decode_xer;
xer_type_encoder_f NRPaging_eDRX_Cycle_Inactive_encode_xer;
jer_type_encoder_f NRPaging_eDRX_Cycle_Inactive_encode_jer;
oer_type_decoder_f NRPaging_eDRX_Cycle_Inactive_decode_oer;
oer_type_encoder_f NRPaging_eDRX_Cycle_Inactive_encode_oer;
per_type_decoder_f NRPaging_eDRX_Cycle_Inactive_decode_uper;
per_type_encoder_f NRPaging_eDRX_Cycle_Inactive_encode_uper;
per_type_decoder_f NRPaging_eDRX_Cycle_Inactive_decode_aper;
per_type_encoder_f NRPaging_eDRX_Cycle_Inactive_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPaging_eDRX_Cycle_Inactive_H_ */
#include "asn_internal.h"
