/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_PDCMeasuredResultsList_H_
#define	_PDCMeasuredResultsList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDCMeasuredResults_Item;

/* PDCMeasuredResultsList */
typedef struct PDCMeasuredResultsList {
	A_SEQUENCE_OF(struct PDCMeasuredResults_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDCMeasuredResultsList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDCMeasuredResultsList;
extern asn_SET_OF_specifics_t asn_SPC_PDCMeasuredResultsList_specs_1;
extern asn_TYPE_member_t asn_MBR_PDCMeasuredResultsList_1[1];
extern asn_per_constraints_t asn_PER_type_PDCMeasuredResultsList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PDCMeasuredResultsList_H_ */
#include "asn_internal.h"
