/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_RLFReportInformationItem_H_
#define	_RLFReportInformationItem_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NRUERLFReportContainer.h"
#include "GNB-DU-UE-F1AP-ID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* RLFReportInformationItem */
typedef struct RLFReportInformationItem {
	NRUERLFReportContainer_t	 nRUERLFReportContainer;
	GNB_DU_UE_F1AP_ID_t	*uEAssitantIdentifier;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLFReportInformationItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLFReportInformationItem;
extern asn_SEQUENCE_specifics_t asn_SPC_RLFReportInformationItem_specs_1;
extern asn_TYPE_member_t asn_MBR_RLFReportInformationItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RLFReportInformationItem_H_ */
#include "asn_internal.h"
