/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_TRPTEG_Item_H_
#define	_TRPTEG_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TRP-Tx-TEGInformation.h"
#include "PRS-Resource-Set-ID.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;
struct DLPRSResourceID_Item;

/* TRPTEG-Item */
typedef struct TRPTEG_Item {
	TRP_Tx_TEGInformation_t	 tRP_Tx_TEGInformation;
	PRS_Resource_Set_ID_t	 dl_PRSResourceSetID;
	struct TRPTEG_Item__dl_PRSResourceID_List {
		A_SEQUENCE_OF(struct DLPRSResourceID_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *dl_PRSResourceID_List;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TRPTEG_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TRPTEG_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_TRPTEG_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_TRPTEG_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _TRPTEG_Item_H_ */
#include "asn_internal.h"
