/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_UL_RTOA_MeasurementItem_H_
#define	_UL_RTOA_MeasurementItem_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_RTOA_MeasurementItem_PR {
	UL_RTOA_MeasurementItem_PR_NOTHING,	/* No components present */
	UL_RTOA_MeasurementItem_PR_k0,
	UL_RTOA_MeasurementItem_PR_k1,
	UL_RTOA_MeasurementItem_PR_k2,
	UL_RTOA_MeasurementItem_PR_k3,
	UL_RTOA_MeasurementItem_PR_k4,
	UL_RTOA_MeasurementItem_PR_k5,
	UL_RTOA_MeasurementItem_PR_choice_extension
} UL_RTOA_MeasurementItem_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* UL-RTOA-MeasurementItem */
typedef struct UL_RTOA_MeasurementItem {
	UL_RTOA_MeasurementItem_PR present;
	union UL_RTOA_MeasurementItem_u {
		long	 k0;
		long	 k1;
		long	 k2;
		long	 k3;
		long	 k4;
		long	 k5;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_RTOA_MeasurementItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_RTOA_MeasurementItem;
extern asn_CHOICE_specifics_t asn_SPC_UL_RTOA_MeasurementItem_specs_1;
extern asn_TYPE_member_t asn_MBR_UL_RTOA_MeasurementItem_1[7];
extern asn_per_constraints_t asn_PER_type_UL_RTOA_MeasurementItem_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _UL_RTOA_MeasurementItem_H_ */
#include "asn_internal.h"
