/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1AP-IEs.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -gen-APER`
 */

#ifndef	_ZoAInformation_H_
#define	_ZoAInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LCS_to_GCS_Translation;
struct ProtocolExtensionContainer;

/* ZoAInformation */
typedef struct ZoAInformation {
	long	 zenithAoA;
	struct LCS_to_GCS_Translation	*lCS_to_GCS_Translation;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ZoAInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ZoAInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_ZoAInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_ZoAInformation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ZoAInformation_H_ */
#include "asn_internal.h"
