// @generated Code generated by gen-atomicint.

// Copyright (c) 2020 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:23
package atomic

//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:23
import (
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:23
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:23
)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:23
import (
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:23
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:23
)

import (
	"encoding/json"
	"strconv"
	"sync/atomic"
)

// Uint64 is an atomic wrapper around uint64.
type Uint64 struct {
	_	nocmp	// disallow non-atomic comparison

	v	uint64
}

// NewUint64 creates a new Uint64.
func NewUint64(i uint64) *Uint64 {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:39
	_go_fuzz_dep_.CoverTab[130470]++
										return &Uint64{v: i}
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:40
	// _ = "end of CoverTab[130470]"
}

// Load atomically loads the wrapped value.
func (i *Uint64) Load() uint64 {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:44
	_go_fuzz_dep_.CoverTab[130471]++
										return atomic.LoadUint64(&i.v)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:45
	// _ = "end of CoverTab[130471]"
}

// Add atomically adds to the wrapped uint64 and returns the new value.
func (i *Uint64) Add(n uint64) uint64 {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:49
	_go_fuzz_dep_.CoverTab[130472]++
										return atomic.AddUint64(&i.v, n)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:50
	// _ = "end of CoverTab[130472]"
}

// Sub atomically subtracts from the wrapped uint64 and returns the new value.
func (i *Uint64) Sub(n uint64) uint64 {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:54
	_go_fuzz_dep_.CoverTab[130473]++
										return atomic.AddUint64(&i.v, ^(n - 1))
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:55
	// _ = "end of CoverTab[130473]"
}

// Inc atomically increments the wrapped uint64 and returns the new value.
func (i *Uint64) Inc() uint64 {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:59
	_go_fuzz_dep_.CoverTab[130474]++
										return i.Add(1)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:60
	// _ = "end of CoverTab[130474]"
}

// Dec atomically decrements the wrapped uint64 and returns the new value.
func (i *Uint64) Dec() uint64 {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:64
	_go_fuzz_dep_.CoverTab[130475]++
										return i.Sub(1)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:65
	// _ = "end of CoverTab[130475]"
}

// CAS is an atomic compare-and-swap.
func (i *Uint64) CAS(old, new uint64) bool {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:69
	_go_fuzz_dep_.CoverTab[130476]++
										return atomic.CompareAndSwapUint64(&i.v, old, new)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:70
	// _ = "end of CoverTab[130476]"
}

// Store atomically stores the passed value.
func (i *Uint64) Store(n uint64) {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:74
	_go_fuzz_dep_.CoverTab[130477]++
										atomic.StoreUint64(&i.v, n)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:75
	// _ = "end of CoverTab[130477]"
}

// Swap atomically swaps the wrapped uint64 and returns the old value.
func (i *Uint64) Swap(n uint64) uint64 {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:79
	_go_fuzz_dep_.CoverTab[130478]++
										return atomic.SwapUint64(&i.v, n)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:80
	// _ = "end of CoverTab[130478]"
}

// MarshalJSON encodes the wrapped uint64 into JSON.
func (i *Uint64) MarshalJSON() ([]byte, error) {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:84
	_go_fuzz_dep_.CoverTab[130479]++
										return json.Marshal(i.Load())
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:85
	// _ = "end of CoverTab[130479]"
}

// UnmarshalJSON decodes JSON into the wrapped uint64.
func (i *Uint64) UnmarshalJSON(b []byte) error {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:89
	_go_fuzz_dep_.CoverTab[130480]++
										var v uint64
										if err := json.Unmarshal(b, &v); err != nil {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:91
		_go_fuzz_dep_.CoverTab[130482]++
											return err
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:92
		// _ = "end of CoverTab[130482]"
	} else {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:93
		_go_fuzz_dep_.CoverTab[130483]++
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:93
		// _ = "end of CoverTab[130483]"
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:93
	}
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:93
	// _ = "end of CoverTab[130480]"
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:93
	_go_fuzz_dep_.CoverTab[130481]++
										i.Store(v)
										return nil
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:95
	// _ = "end of CoverTab[130481]"
}

// String encodes the wrapped value as a string.
func (i *Uint64) String() string {
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:99
	_go_fuzz_dep_.CoverTab[130484]++
										v := i.Load()
										return strconv.FormatUint(uint64(v), 10)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:101
	// _ = "end of CoverTab[130484]"
}

//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:102
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/go.uber.org/atomic@v1.7.0/uint64.go:102
var _ = _go_fuzz_dep_.CoverTab
