{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

*/ -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: tb-node-cache-config
  labels:
    name: tb-node-cache-config
data:
  CACHE_TYPE: redis
  REDIS_HOST: tb-redis