{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

*/ -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb-mqtt-transport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-mqtt-transport
  template:
    metadata:
      labels:
        app: tb-mqtt-transport
    spec:
      serviceAccountName: thingsboard
      volumes:
        - name: tb-mqtt-transport-config
          configMap:
            name: tb-mqtt-transport-config
            items:
              - key: conf
                path:  tb-mqtt-transport.conf
              - key: logback
                path:  logback.xml
      initContainers:
        - name: tb-mqtt-transport-dep-check
          image: {{ .Values.images.tags.depCheck }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: COMMAND
              value: "echo done"
            - name: DEPENDENCY_POD_JSON
              value: '[{"labels": {"app": "tb-kafka"}, "requireSameNode": false}]'
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
      containers:
        - name: server
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          image: {{ .Values.images.tags.mqttTransport }}
          ports:
            - containerPort: {{ .Values.config.transports.mqtt.port }}
              name: mqtt
          env:
            - name: TB_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TB_QUEUE_TYPE
              value: "kafka"
            - name: MQTT_BIND_ADDRESS
              value: {{ .Values.config.transports.mqtt.bindAddr | quote}}
            - name: MQTT_BIND_PORT
              value: {{ .Values.config.transports.mqtt.port | quote}}
            - name: MQTT_TIMEOUT
              value: {{ .Values.config.transports.mqtt.timeout | quote}}
            - name: TB_KAFKA_SERVERS
              value: "tb-kafka:{{ .Values.config.kafka.ports.outPort }}"
          volumeMounts:
            - mountPath: /config
              name: tb-mqtt-transport-config
          readinessProbe:
            periodSeconds: 20
            tcpSocket:
              port: {{ .Values.config.transports.mqtt.port }}
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 20
            tcpSocket:
              port: {{ .Values.config.transports.mqtt.port }}
      restartPolicy: Always