{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

*/ -}}

---
apiVersion: v1
kind: Service
metadata:
  name: tb-node
spec:
  type: ClusterIP
  selector:
    app: tb-node
  ports:
    - port: {{ .Values.config.tbNode.ports.http }}
      name: http
    - port: {{ .Values.config.tbNode.ports.rpc }}
      name: rpc

---
apiVersion: v1
kind: Service
metadata:
  name: tb-node-external
spec:
  type: NodePort
  selector:
    app: tb-node
  ports:
{{- if .Values.config.tbNode.nodePort.http.enabled }}
    - port: {{ .Values.config.tbNode.ports.http }}
      name: http
      protocol: TCP
      nodePort: {{ .Values.config.tbNode.nodePort.http.port }}
{{- end }}
    {{- if .Values.config.tbNode.nodePort.rpc.enabled }}
    - port: {{ .Values.config.tbNode.ports.rpc }}
      name: http
      protocol: TCP
      nodePort: {{ .Values.config.tbNode.nodePort.rpc.port }}
  {{- end }}