{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

*/ -}}
---
apiVersion: v1
kind: Service
metadata:
  name: tb-kafka
spec:
  type: ClusterIP
  selector:
    app: tb-kafka
  ports:
    - name: tb-kafka-port
      port: {{ .Values.config.kafka.ports.outPort }}