{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

*/ -}}

---
apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-transport
spec:
  type: ClusterIP
  selector:
    app: tb-mqtt-transport
  ports:
    - port: {{ .Values.config.transports.mqtt.port }}
      name: mqtt

---
apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-transport-external
spec:
  type: NodePort
  selector:
    app: tb-mqtt-transport
  ports:
{{- if .Values.config.transports.mqtt.nodePort.enabled }}
    - port: {{ .Values.config.transports.mqtt.port }}
      name: mqtt
      protocol: TCP
      nodePort: {{ .Values.config.transports.mqtt.nodePort.port }}
{{- end }}