{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

*/ -}}

---
apiVersion: v1
kind: Service
metadata:
  name: tb-http-transport
spec:
  type: ClusterIP
  selector:
    app: tb-http-transport
  ports:
    - port: {{ .Values.config.transports.http.port }}
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: tb-http-transport-external
spec:
  type: NodePort
  selector:
    app: tb-http-transport
  ports:
    {{- if .Values.config.transports.http.nodePort.enabled }}
    - port: {{ .Values.config.transports.http.port }}
      name: http
      protocol: TCP
      nodePort: {{ .Values.config.transports.http.nodePort.port }}
  {{- end }}