{{- /*

# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

*/ -}}

---
apiVersion: v1
kind: Service
metadata:
  name: accelleran-cbrs-redis
  labels:
{{ tuple "accelleran-cbrs-redis" . | include "accelleran-cbrs-common.metadata_labels" | indent 4 }}
spec:
  selector:
{{ tuple "accelleran-cbrs-redis" . | include "accelleran-cbrs-common.metadata_labels" | indent 4 }}
  ports:
  - name: redis-port
    port: {{ .Values.config.redis.ports.redisPort.port }}
    protocol: {{ .Values.config.redis.ports.redisPort.protocol }}

---
apiVersion: v1
kind: Service
metadata:
  name: accelleran-cbrs-redis-exernal
  labels:
{{ tuple "accelleran-cbrs-redis" . | include "accelleran-cbrs-common.metadata_labels" | indent 4 }}
spec:
  selector:
{{ tuple "accelleran-cbrs-redis" . | include "accelleran-cbrs-common.metadata_labels" | indent 4 }}
  type: NodePort
  ports:
  - name: redis-port
    port: {{ .Values.config.redis.ports.redisPort.port }}
    nodePort: {{ .Values.config.redis.ports.redisPort.nodePort }}
    protocol: {{ .Values.config.redis.ports.redisPort.protocol }}
