// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:5
package impl

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:5
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:5
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:5
)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:5
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:5
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:5
)

import (
	"fmt"
	"reflect"

	"google.golang.org/protobuf/reflect/protoreflect"
)

// unwrapper unwraps the value to the underlying value.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:14
// This is implemented by List and Map.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:16
type unwrapper interface {
	protoUnwrap() interface{}
}

// A Converter coverts to/from Go reflect.Value types and protobuf protoreflect.Value types.
type Converter interface {
	// PBValueOf converts a reflect.Value to a protoreflect.Value.
	PBValueOf(reflect.Value) protoreflect.Value

	// GoValueOf converts a protoreflect.Value to a reflect.Value.
	GoValueOf(protoreflect.Value) reflect.Value

	// IsValidPB returns whether a protoreflect.Value is compatible with this type.
	IsValidPB(protoreflect.Value) bool

	// IsValidGo returns whether a reflect.Value is compatible with this type.
	IsValidGo(reflect.Value) bool

	// New returns a new field value.
	// For scalars, it returns the default value of the field.
	// For composite types, it returns a new mutable value.
	New() protoreflect.Value

	// Zero returns a new field value.
	// For scalars, it returns the default value of the field.
	// For composite types, it returns an immutable, empty value.
	Zero() protoreflect.Value
}

// NewConverter matches a Go type with a protobuf field and returns a Converter
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:45
// that converts between the two. Enums must be a named int32 kind that
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:45
// implements protoreflect.Enum, and messages must be pointer to a named
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:45
// struct type that implements protoreflect.ProtoMessage.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:45
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:45
// This matcher deliberately supports a wider range of Go types than what
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:45
// protoc-gen-go historically generated to be able to automatically wrap some
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:45
// v1 messages generated by other forks of protoc-gen-go.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:53
func NewConverter(t reflect.Type, fd protoreflect.FieldDescriptor) Converter {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:53
	_go_fuzz_dep_.CoverTab[56882]++
													switch {
	case fd.IsList():
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:55
		_go_fuzz_dep_.CoverTab[56884]++
														return newListConverter(t, fd)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:56
		// _ = "end of CoverTab[56884]"
	case fd.IsMap():
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:57
		_go_fuzz_dep_.CoverTab[56885]++
														return newMapConverter(t, fd)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:58
		// _ = "end of CoverTab[56885]"
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:59
		_go_fuzz_dep_.CoverTab[56886]++
														return newSingularConverter(t, fd)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:60
		// _ = "end of CoverTab[56886]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:61
	// _ = "end of CoverTab[56882]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:61
	_go_fuzz_dep_.CoverTab[56883]++
													panic(fmt.Sprintf("invalid Go type %v for field %v", t, fd.FullName()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:62
	// _ = "end of CoverTab[56883]"
}

var (
	boolType	= reflect.TypeOf(bool(false))
	int32Type	= reflect.TypeOf(int32(0))
	int64Type	= reflect.TypeOf(int64(0))
	uint32Type	= reflect.TypeOf(uint32(0))
	uint64Type	= reflect.TypeOf(uint64(0))
	float32Type	= reflect.TypeOf(float32(0))
	float64Type	= reflect.TypeOf(float64(0))
	stringType	= reflect.TypeOf(string(""))
	bytesType	= reflect.TypeOf([]byte(nil))
	byteType	= reflect.TypeOf(byte(0))
)

var (
	boolZero	= protoreflect.ValueOfBool(false)
	int32Zero	= protoreflect.ValueOfInt32(0)
	int64Zero	= protoreflect.ValueOfInt64(0)
	uint32Zero	= protoreflect.ValueOfUint32(0)
	uint64Zero	= protoreflect.ValueOfUint64(0)
	float32Zero	= protoreflect.ValueOfFloat32(0)
	float64Zero	= protoreflect.ValueOfFloat64(0)
	stringZero	= protoreflect.ValueOfString("")
	bytesZero	= protoreflect.ValueOfBytes(nil)
)

func newSingularConverter(t reflect.Type, fd protoreflect.FieldDescriptor) Converter {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:90
	_go_fuzz_dep_.CoverTab[56887]++
													defVal := func(fd protoreflect.FieldDescriptor, zero protoreflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:91
		_go_fuzz_dep_.CoverTab[56890]++
														if fd.Cardinality() == protoreflect.Repeated {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:92
			_go_fuzz_dep_.CoverTab[56892]++

															return zero
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:94
			// _ = "end of CoverTab[56892]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:95
			_go_fuzz_dep_.CoverTab[56893]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:95
			// _ = "end of CoverTab[56893]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:95
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:95
		// _ = "end of CoverTab[56890]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:95
		_go_fuzz_dep_.CoverTab[56891]++
														return fd.Default()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:96
		// _ = "end of CoverTab[56891]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:97
	// _ = "end of CoverTab[56887]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:97
	_go_fuzz_dep_.CoverTab[56888]++
													switch fd.Kind() {
	case protoreflect.BoolKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:99
		_go_fuzz_dep_.CoverTab[56894]++
														if t.Kind() == reflect.Bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:100
			_go_fuzz_dep_.CoverTab[56906]++
															return &boolConverter{t, defVal(fd, boolZero)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:101
			// _ = "end of CoverTab[56906]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:102
			_go_fuzz_dep_.CoverTab[56907]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:102
			// _ = "end of CoverTab[56907]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:102
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:102
		// _ = "end of CoverTab[56894]"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:103
		_go_fuzz_dep_.CoverTab[56895]++
														if t.Kind() == reflect.Int32 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:104
			_go_fuzz_dep_.CoverTab[56908]++
															return &int32Converter{t, defVal(fd, int32Zero)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:105
			// _ = "end of CoverTab[56908]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:106
			_go_fuzz_dep_.CoverTab[56909]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:106
			// _ = "end of CoverTab[56909]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:106
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:106
		// _ = "end of CoverTab[56895]"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:107
		_go_fuzz_dep_.CoverTab[56896]++
														if t.Kind() == reflect.Int64 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:108
			_go_fuzz_dep_.CoverTab[56910]++
															return &int64Converter{t, defVal(fd, int64Zero)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:109
			// _ = "end of CoverTab[56910]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:110
			_go_fuzz_dep_.CoverTab[56911]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:110
			// _ = "end of CoverTab[56911]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:110
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:110
		// _ = "end of CoverTab[56896]"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:111
		_go_fuzz_dep_.CoverTab[56897]++
														if t.Kind() == reflect.Uint32 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:112
			_go_fuzz_dep_.CoverTab[56912]++
															return &uint32Converter{t, defVal(fd, uint32Zero)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:113
			// _ = "end of CoverTab[56912]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:114
			_go_fuzz_dep_.CoverTab[56913]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:114
			// _ = "end of CoverTab[56913]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:114
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:114
		// _ = "end of CoverTab[56897]"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:115
		_go_fuzz_dep_.CoverTab[56898]++
														if t.Kind() == reflect.Uint64 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:116
			_go_fuzz_dep_.CoverTab[56914]++
															return &uint64Converter{t, defVal(fd, uint64Zero)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:117
			// _ = "end of CoverTab[56914]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:118
			_go_fuzz_dep_.CoverTab[56915]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:118
			// _ = "end of CoverTab[56915]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:118
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:118
		// _ = "end of CoverTab[56898]"
	case protoreflect.FloatKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:119
		_go_fuzz_dep_.CoverTab[56899]++
														if t.Kind() == reflect.Float32 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:120
			_go_fuzz_dep_.CoverTab[56916]++
															return &float32Converter{t, defVal(fd, float32Zero)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:121
			// _ = "end of CoverTab[56916]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:122
			_go_fuzz_dep_.CoverTab[56917]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:122
			// _ = "end of CoverTab[56917]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:122
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:122
		// _ = "end of CoverTab[56899]"
	case protoreflect.DoubleKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:123
		_go_fuzz_dep_.CoverTab[56900]++
														if t.Kind() == reflect.Float64 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:124
			_go_fuzz_dep_.CoverTab[56918]++
															return &float64Converter{t, defVal(fd, float64Zero)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:125
			// _ = "end of CoverTab[56918]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:126
			_go_fuzz_dep_.CoverTab[56919]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:126
			// _ = "end of CoverTab[56919]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:126
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:126
		// _ = "end of CoverTab[56900]"
	case protoreflect.StringKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:127
		_go_fuzz_dep_.CoverTab[56901]++
														if t.Kind() == reflect.String || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:128
			_go_fuzz_dep_.CoverTab[56920]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:128
			return (t.Kind() == reflect.Slice && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:128
				_go_fuzz_dep_.CoverTab[56921]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:128
				return t.Elem() == byteType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:128
				// _ = "end of CoverTab[56921]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:128
			}())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:128
			// _ = "end of CoverTab[56920]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:128
		}() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:128
			_go_fuzz_dep_.CoverTab[56922]++
															return &stringConverter{t, defVal(fd, stringZero)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:129
			// _ = "end of CoverTab[56922]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:130
			_go_fuzz_dep_.CoverTab[56923]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:130
			// _ = "end of CoverTab[56923]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:130
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:130
		// _ = "end of CoverTab[56901]"
	case protoreflect.BytesKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:131
		_go_fuzz_dep_.CoverTab[56902]++
														if t.Kind() == reflect.String || func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:132
			_go_fuzz_dep_.CoverTab[56924]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:132
			return (t.Kind() == reflect.Slice && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:132
				_go_fuzz_dep_.CoverTab[56925]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:132
				return t.Elem() == byteType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:132
				// _ = "end of CoverTab[56925]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:132
			}())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:132
			// _ = "end of CoverTab[56924]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:132
		}() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:132
			_go_fuzz_dep_.CoverTab[56926]++
															return &bytesConverter{t, defVal(fd, bytesZero)}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:133
			// _ = "end of CoverTab[56926]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:134
			_go_fuzz_dep_.CoverTab[56927]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:134
			// _ = "end of CoverTab[56927]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:134
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:134
		// _ = "end of CoverTab[56902]"
	case protoreflect.EnumKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:135
		_go_fuzz_dep_.CoverTab[56903]++

														if t.Kind() == reflect.Int32 {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:137
			_go_fuzz_dep_.CoverTab[56928]++
															return newEnumConverter(t, fd)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:138
			// _ = "end of CoverTab[56928]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:139
			_go_fuzz_dep_.CoverTab[56929]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:139
			// _ = "end of CoverTab[56929]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:139
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:139
		// _ = "end of CoverTab[56903]"
	case protoreflect.MessageKind, protoreflect.GroupKind:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:140
		_go_fuzz_dep_.CoverTab[56904]++
														return newMessageConverter(t)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:141
		// _ = "end of CoverTab[56904]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:141
	default:
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:141
		_go_fuzz_dep_.CoverTab[56905]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:141
		// _ = "end of CoverTab[56905]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:142
	// _ = "end of CoverTab[56888]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:142
	_go_fuzz_dep_.CoverTab[56889]++
													panic(fmt.Sprintf("invalid Go type %v for field %v", t, fd.FullName()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:143
	// _ = "end of CoverTab[56889]"
}

type boolConverter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func (c *boolConverter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:151
	_go_fuzz_dep_.CoverTab[56930]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:152
		_go_fuzz_dep_.CoverTab[56932]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:153
		// _ = "end of CoverTab[56932]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:154
		_go_fuzz_dep_.CoverTab[56933]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:154
		// _ = "end of CoverTab[56933]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:154
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:154
	// _ = "end of CoverTab[56930]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:154
	_go_fuzz_dep_.CoverTab[56931]++
													return protoreflect.ValueOfBool(v.Bool())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:155
	// _ = "end of CoverTab[56931]"
}
func (c *boolConverter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:157
	_go_fuzz_dep_.CoverTab[56934]++
													return reflect.ValueOf(v.Bool()).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:158
	// _ = "end of CoverTab[56934]"
}
func (c *boolConverter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:160
	_go_fuzz_dep_.CoverTab[56935]++
													_, ok := v.Interface().(bool)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:162
	// _ = "end of CoverTab[56935]"
}
func (c *boolConverter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:164
	_go_fuzz_dep_.CoverTab[56936]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:165
		_go_fuzz_dep_.CoverTab[56937]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:165
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:165
		// _ = "end of CoverTab[56937]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:165
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:165
	// _ = "end of CoverTab[56936]"
}
func (c *boolConverter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:167
	_go_fuzz_dep_.CoverTab[56938]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:167
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:167
	// _ = "end of CoverTab[56938]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:167
}
func (c *boolConverter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:168
	_go_fuzz_dep_.CoverTab[56939]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:168
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:168
	// _ = "end of CoverTab[56939]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:168
}

type int32Converter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func (c *int32Converter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:175
	_go_fuzz_dep_.CoverTab[56940]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:176
		_go_fuzz_dep_.CoverTab[56942]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:177
		// _ = "end of CoverTab[56942]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:178
		_go_fuzz_dep_.CoverTab[56943]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:178
		// _ = "end of CoverTab[56943]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:178
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:178
	// _ = "end of CoverTab[56940]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:178
	_go_fuzz_dep_.CoverTab[56941]++
													return protoreflect.ValueOfInt32(int32(v.Int()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:179
	// _ = "end of CoverTab[56941]"
}
func (c *int32Converter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:181
	_go_fuzz_dep_.CoverTab[56944]++
													return reflect.ValueOf(int32(v.Int())).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:182
	// _ = "end of CoverTab[56944]"
}
func (c *int32Converter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:184
	_go_fuzz_dep_.CoverTab[56945]++
													_, ok := v.Interface().(int32)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:186
	// _ = "end of CoverTab[56945]"
}
func (c *int32Converter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:188
	_go_fuzz_dep_.CoverTab[56946]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:189
		_go_fuzz_dep_.CoverTab[56947]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:189
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:189
		// _ = "end of CoverTab[56947]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:189
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:189
	// _ = "end of CoverTab[56946]"
}
func (c *int32Converter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:191
	_go_fuzz_dep_.CoverTab[56948]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:191
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:191
	// _ = "end of CoverTab[56948]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:191
}
func (c *int32Converter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:192
	_go_fuzz_dep_.CoverTab[56949]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:192
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:192
	// _ = "end of CoverTab[56949]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:192
}

type int64Converter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func (c *int64Converter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:199
	_go_fuzz_dep_.CoverTab[56950]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:200
		_go_fuzz_dep_.CoverTab[56952]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:201
		// _ = "end of CoverTab[56952]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:202
		_go_fuzz_dep_.CoverTab[56953]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:202
		// _ = "end of CoverTab[56953]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:202
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:202
	// _ = "end of CoverTab[56950]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:202
	_go_fuzz_dep_.CoverTab[56951]++
													return protoreflect.ValueOfInt64(int64(v.Int()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:203
	// _ = "end of CoverTab[56951]"
}
func (c *int64Converter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:205
	_go_fuzz_dep_.CoverTab[56954]++
													return reflect.ValueOf(int64(v.Int())).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:206
	// _ = "end of CoverTab[56954]"
}
func (c *int64Converter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:208
	_go_fuzz_dep_.CoverTab[56955]++
													_, ok := v.Interface().(int64)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:210
	// _ = "end of CoverTab[56955]"
}
func (c *int64Converter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:212
	_go_fuzz_dep_.CoverTab[56956]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:213
		_go_fuzz_dep_.CoverTab[56957]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:213
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:213
		// _ = "end of CoverTab[56957]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:213
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:213
	// _ = "end of CoverTab[56956]"
}
func (c *int64Converter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:215
	_go_fuzz_dep_.CoverTab[56958]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:215
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:215
	// _ = "end of CoverTab[56958]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:215
}
func (c *int64Converter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:216
	_go_fuzz_dep_.CoverTab[56959]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:216
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:216
	// _ = "end of CoverTab[56959]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:216
}

type uint32Converter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func (c *uint32Converter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:223
	_go_fuzz_dep_.CoverTab[56960]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:224
		_go_fuzz_dep_.CoverTab[56962]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:225
		// _ = "end of CoverTab[56962]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:226
		_go_fuzz_dep_.CoverTab[56963]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:226
		// _ = "end of CoverTab[56963]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:226
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:226
	// _ = "end of CoverTab[56960]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:226
	_go_fuzz_dep_.CoverTab[56961]++
													return protoreflect.ValueOfUint32(uint32(v.Uint()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:227
	// _ = "end of CoverTab[56961]"
}
func (c *uint32Converter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:229
	_go_fuzz_dep_.CoverTab[56964]++
													return reflect.ValueOf(uint32(v.Uint())).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:230
	// _ = "end of CoverTab[56964]"
}
func (c *uint32Converter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:232
	_go_fuzz_dep_.CoverTab[56965]++
													_, ok := v.Interface().(uint32)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:234
	// _ = "end of CoverTab[56965]"
}
func (c *uint32Converter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:236
	_go_fuzz_dep_.CoverTab[56966]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:237
		_go_fuzz_dep_.CoverTab[56967]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:237
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:237
		// _ = "end of CoverTab[56967]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:237
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:237
	// _ = "end of CoverTab[56966]"
}
func (c *uint32Converter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:239
	_go_fuzz_dep_.CoverTab[56968]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:239
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:239
	// _ = "end of CoverTab[56968]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:239
}
func (c *uint32Converter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:240
	_go_fuzz_dep_.CoverTab[56969]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:240
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:240
	// _ = "end of CoverTab[56969]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:240
}

type uint64Converter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func (c *uint64Converter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:247
	_go_fuzz_dep_.CoverTab[56970]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:248
		_go_fuzz_dep_.CoverTab[56972]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:249
		// _ = "end of CoverTab[56972]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:250
		_go_fuzz_dep_.CoverTab[56973]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:250
		// _ = "end of CoverTab[56973]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:250
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:250
	// _ = "end of CoverTab[56970]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:250
	_go_fuzz_dep_.CoverTab[56971]++
													return protoreflect.ValueOfUint64(uint64(v.Uint()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:251
	// _ = "end of CoverTab[56971]"
}
func (c *uint64Converter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:253
	_go_fuzz_dep_.CoverTab[56974]++
													return reflect.ValueOf(uint64(v.Uint())).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:254
	// _ = "end of CoverTab[56974]"
}
func (c *uint64Converter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:256
	_go_fuzz_dep_.CoverTab[56975]++
													_, ok := v.Interface().(uint64)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:258
	// _ = "end of CoverTab[56975]"
}
func (c *uint64Converter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:260
	_go_fuzz_dep_.CoverTab[56976]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:261
		_go_fuzz_dep_.CoverTab[56977]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:261
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:261
		// _ = "end of CoverTab[56977]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:261
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:261
	// _ = "end of CoverTab[56976]"
}
func (c *uint64Converter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:263
	_go_fuzz_dep_.CoverTab[56978]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:263
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:263
	// _ = "end of CoverTab[56978]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:263
}
func (c *uint64Converter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:264
	_go_fuzz_dep_.CoverTab[56979]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:264
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:264
	// _ = "end of CoverTab[56979]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:264
}

type float32Converter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func (c *float32Converter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:271
	_go_fuzz_dep_.CoverTab[56980]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:272
		_go_fuzz_dep_.CoverTab[56982]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:273
		// _ = "end of CoverTab[56982]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:274
		_go_fuzz_dep_.CoverTab[56983]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:274
		// _ = "end of CoverTab[56983]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:274
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:274
	// _ = "end of CoverTab[56980]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:274
	_go_fuzz_dep_.CoverTab[56981]++
													return protoreflect.ValueOfFloat32(float32(v.Float()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:275
	// _ = "end of CoverTab[56981]"
}
func (c *float32Converter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:277
	_go_fuzz_dep_.CoverTab[56984]++
													return reflect.ValueOf(float32(v.Float())).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:278
	// _ = "end of CoverTab[56984]"
}
func (c *float32Converter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:280
	_go_fuzz_dep_.CoverTab[56985]++
													_, ok := v.Interface().(float32)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:282
	// _ = "end of CoverTab[56985]"
}
func (c *float32Converter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:284
	_go_fuzz_dep_.CoverTab[56986]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:285
		_go_fuzz_dep_.CoverTab[56987]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:285
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:285
		// _ = "end of CoverTab[56987]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:285
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:285
	// _ = "end of CoverTab[56986]"
}
func (c *float32Converter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:287
	_go_fuzz_dep_.CoverTab[56988]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:287
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:287
	// _ = "end of CoverTab[56988]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:287
}
func (c *float32Converter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:288
	_go_fuzz_dep_.CoverTab[56989]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:288
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:288
	// _ = "end of CoverTab[56989]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:288
}

type float64Converter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func (c *float64Converter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:295
	_go_fuzz_dep_.CoverTab[56990]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:296
		_go_fuzz_dep_.CoverTab[56992]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:297
		// _ = "end of CoverTab[56992]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:298
		_go_fuzz_dep_.CoverTab[56993]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:298
		// _ = "end of CoverTab[56993]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:298
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:298
	// _ = "end of CoverTab[56990]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:298
	_go_fuzz_dep_.CoverTab[56991]++
													return protoreflect.ValueOfFloat64(float64(v.Float()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:299
	// _ = "end of CoverTab[56991]"
}
func (c *float64Converter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:301
	_go_fuzz_dep_.CoverTab[56994]++
													return reflect.ValueOf(float64(v.Float())).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:302
	// _ = "end of CoverTab[56994]"
}
func (c *float64Converter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:304
	_go_fuzz_dep_.CoverTab[56995]++
													_, ok := v.Interface().(float64)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:306
	// _ = "end of CoverTab[56995]"
}
func (c *float64Converter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:308
	_go_fuzz_dep_.CoverTab[56996]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:309
		_go_fuzz_dep_.CoverTab[56997]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:309
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:309
		// _ = "end of CoverTab[56997]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:309
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:309
	// _ = "end of CoverTab[56996]"
}
func (c *float64Converter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:311
	_go_fuzz_dep_.CoverTab[56998]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:311
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:311
	// _ = "end of CoverTab[56998]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:311
}
func (c *float64Converter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:312
	_go_fuzz_dep_.CoverTab[56999]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:312
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:312
	// _ = "end of CoverTab[56999]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:312
}

type stringConverter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func (c *stringConverter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:319
	_go_fuzz_dep_.CoverTab[57000]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:320
		_go_fuzz_dep_.CoverTab[57002]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:321
		// _ = "end of CoverTab[57002]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:322
		_go_fuzz_dep_.CoverTab[57003]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:322
		// _ = "end of CoverTab[57003]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:322
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:322
	// _ = "end of CoverTab[57000]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:322
	_go_fuzz_dep_.CoverTab[57001]++
													return protoreflect.ValueOfString(v.Convert(stringType).String())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:323
	// _ = "end of CoverTab[57001]"
}
func (c *stringConverter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:325
	_go_fuzz_dep_.CoverTab[57004]++

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:328
	s := v.Interface().(string)
	if c.goType.Kind() == reflect.Slice && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:329
		_go_fuzz_dep_.CoverTab[57006]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:329
		return s == ""
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:329
		// _ = "end of CoverTab[57006]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:329
	}() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:329
		_go_fuzz_dep_.CoverTab[57007]++
														return reflect.Zero(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:330
		// _ = "end of CoverTab[57007]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:331
		_go_fuzz_dep_.CoverTab[57008]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:331
		// _ = "end of CoverTab[57008]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:331
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:331
	// _ = "end of CoverTab[57004]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:331
	_go_fuzz_dep_.CoverTab[57005]++
													return reflect.ValueOf(s).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:332
	// _ = "end of CoverTab[57005]"
}
func (c *stringConverter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:334
	_go_fuzz_dep_.CoverTab[57009]++
													_, ok := v.Interface().(string)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:336
	// _ = "end of CoverTab[57009]"
}
func (c *stringConverter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:338
	_go_fuzz_dep_.CoverTab[57010]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:339
		_go_fuzz_dep_.CoverTab[57011]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:339
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:339
		// _ = "end of CoverTab[57011]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:339
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:339
	// _ = "end of CoverTab[57010]"
}
func (c *stringConverter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:341
	_go_fuzz_dep_.CoverTab[57012]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:341
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:341
	// _ = "end of CoverTab[57012]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:341
}
func (c *stringConverter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:342
	_go_fuzz_dep_.CoverTab[57013]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:342
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:342
	// _ = "end of CoverTab[57013]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:342
}

type bytesConverter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func (c *bytesConverter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:349
	_go_fuzz_dep_.CoverTab[57014]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:350
		_go_fuzz_dep_.CoverTab[57017]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:351
		// _ = "end of CoverTab[57017]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:352
		_go_fuzz_dep_.CoverTab[57018]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:352
		// _ = "end of CoverTab[57018]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:352
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:352
	// _ = "end of CoverTab[57014]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:352
	_go_fuzz_dep_.CoverTab[57015]++
													if c.goType.Kind() == reflect.String && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:353
		_go_fuzz_dep_.CoverTab[57019]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:353
		return v.Len() == 0
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:353
		// _ = "end of CoverTab[57019]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:353
	}() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:353
		_go_fuzz_dep_.CoverTab[57020]++
														return protoreflect.ValueOfBytes(nil)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:354
		// _ = "end of CoverTab[57020]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:355
		_go_fuzz_dep_.CoverTab[57021]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:355
		// _ = "end of CoverTab[57021]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:355
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:355
	// _ = "end of CoverTab[57015]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:355
	_go_fuzz_dep_.CoverTab[57016]++
													return protoreflect.ValueOfBytes(v.Convert(bytesType).Bytes())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:356
	// _ = "end of CoverTab[57016]"
}
func (c *bytesConverter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:358
	_go_fuzz_dep_.CoverTab[57022]++
													return reflect.ValueOf(v.Bytes()).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:359
	// _ = "end of CoverTab[57022]"
}
func (c *bytesConverter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:361
	_go_fuzz_dep_.CoverTab[57023]++
													_, ok := v.Interface().([]byte)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:363
	// _ = "end of CoverTab[57023]"
}
func (c *bytesConverter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:365
	_go_fuzz_dep_.CoverTab[57024]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:366
		_go_fuzz_dep_.CoverTab[57025]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:366
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:366
		// _ = "end of CoverTab[57025]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:366
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:366
	// _ = "end of CoverTab[57024]"
}
func (c *bytesConverter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:368
	_go_fuzz_dep_.CoverTab[57026]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:368
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:368
	// _ = "end of CoverTab[57026]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:368
}
func (c *bytesConverter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:369
	_go_fuzz_dep_.CoverTab[57027]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:369
	return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:369
	// _ = "end of CoverTab[57027]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:369
}

type enumConverter struct {
	goType	reflect.Type
	def	protoreflect.Value
}

func newEnumConverter(goType reflect.Type, fd protoreflect.FieldDescriptor) Converter {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:376
	_go_fuzz_dep_.CoverTab[57028]++
													var def protoreflect.Value
													if fd.Cardinality() == protoreflect.Repeated {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:378
		_go_fuzz_dep_.CoverTab[57030]++
														def = protoreflect.ValueOfEnum(fd.Enum().Values().Get(0).Number())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:379
		// _ = "end of CoverTab[57030]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:380
		_go_fuzz_dep_.CoverTab[57031]++
														def = fd.Default()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:381
		// _ = "end of CoverTab[57031]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:382
	// _ = "end of CoverTab[57028]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:382
	_go_fuzz_dep_.CoverTab[57029]++
													return &enumConverter{goType, def}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:383
	// _ = "end of CoverTab[57029]"
}

func (c *enumConverter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:386
	_go_fuzz_dep_.CoverTab[57032]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:387
		_go_fuzz_dep_.CoverTab[57034]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:388
		// _ = "end of CoverTab[57034]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:389
		_go_fuzz_dep_.CoverTab[57035]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:389
		// _ = "end of CoverTab[57035]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:389
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:389
	// _ = "end of CoverTab[57032]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:389
	_go_fuzz_dep_.CoverTab[57033]++
													return protoreflect.ValueOfEnum(protoreflect.EnumNumber(v.Int()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:390
	// _ = "end of CoverTab[57033]"
}

func (c *enumConverter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:393
	_go_fuzz_dep_.CoverTab[57036]++
													return reflect.ValueOf(v.Enum()).Convert(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:394
	// _ = "end of CoverTab[57036]"
}

func (c *enumConverter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:397
	_go_fuzz_dep_.CoverTab[57037]++
													_, ok := v.Interface().(protoreflect.EnumNumber)
													return ok
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:399
	// _ = "end of CoverTab[57037]"
}

func (c *enumConverter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:402
	_go_fuzz_dep_.CoverTab[57038]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:403
		_go_fuzz_dep_.CoverTab[57039]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:403
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:403
		// _ = "end of CoverTab[57039]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:403
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:403
	// _ = "end of CoverTab[57038]"
}

func (c *enumConverter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:406
	_go_fuzz_dep_.CoverTab[57040]++
													return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:407
	// _ = "end of CoverTab[57040]"
}

func (c *enumConverter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:410
	_go_fuzz_dep_.CoverTab[57041]++
													return c.def
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:411
	// _ = "end of CoverTab[57041]"
}

type messageConverter struct {
	goType reflect.Type
}

func newMessageConverter(goType reflect.Type) Converter {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:418
	_go_fuzz_dep_.CoverTab[57042]++
													return &messageConverter{goType}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:419
	// _ = "end of CoverTab[57042]"
}

func (c *messageConverter) PBValueOf(v reflect.Value) protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:422
	_go_fuzz_dep_.CoverTab[57043]++
													if v.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:423
		_go_fuzz_dep_.CoverTab[57047]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", v.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:424
		// _ = "end of CoverTab[57047]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:425
		_go_fuzz_dep_.CoverTab[57048]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:425
		// _ = "end of CoverTab[57048]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:425
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:425
	// _ = "end of CoverTab[57043]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:425
	_go_fuzz_dep_.CoverTab[57044]++
													if c.isNonPointer() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:426
		_go_fuzz_dep_.CoverTab[57049]++
														if v.CanAddr() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:427
			_go_fuzz_dep_.CoverTab[57050]++
															v = v.Addr()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:428
			// _ = "end of CoverTab[57050]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:429
			_go_fuzz_dep_.CoverTab[57051]++
															v = reflect.Zero(reflect.PtrTo(v.Type()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:430
			// _ = "end of CoverTab[57051]"
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:431
		// _ = "end of CoverTab[57049]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:432
		_go_fuzz_dep_.CoverTab[57052]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:432
		// _ = "end of CoverTab[57052]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:432
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:432
	// _ = "end of CoverTab[57044]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:432
	_go_fuzz_dep_.CoverTab[57045]++
													if m, ok := v.Interface().(protoreflect.ProtoMessage); ok {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:433
		_go_fuzz_dep_.CoverTab[57053]++
														return protoreflect.ValueOfMessage(m.ProtoReflect())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:434
		// _ = "end of CoverTab[57053]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:435
		_go_fuzz_dep_.CoverTab[57054]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:435
		// _ = "end of CoverTab[57054]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:435
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:435
	// _ = "end of CoverTab[57045]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:435
	_go_fuzz_dep_.CoverTab[57046]++
													return protoreflect.ValueOfMessage(legacyWrapMessage(v))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:436
	// _ = "end of CoverTab[57046]"
}

func (c *messageConverter) GoValueOf(v protoreflect.Value) reflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:439
	_go_fuzz_dep_.CoverTab[57055]++
													m := v.Message()
													var rv reflect.Value
													if u, ok := m.(unwrapper); ok {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:442
		_go_fuzz_dep_.CoverTab[57059]++
														rv = reflect.ValueOf(u.protoUnwrap())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:443
		// _ = "end of CoverTab[57059]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:444
		_go_fuzz_dep_.CoverTab[57060]++
														rv = reflect.ValueOf(m.Interface())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:445
		// _ = "end of CoverTab[57060]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:446
	// _ = "end of CoverTab[57055]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:446
	_go_fuzz_dep_.CoverTab[57056]++
													if c.isNonPointer() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:447
		_go_fuzz_dep_.CoverTab[57061]++
														if rv.Type() != reflect.PtrTo(c.goType) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:448
			_go_fuzz_dep_.CoverTab[57063]++
															panic(fmt.Sprintf("invalid type: got %v, want %v", rv.Type(), reflect.PtrTo(c.goType)))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:449
			// _ = "end of CoverTab[57063]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:450
			_go_fuzz_dep_.CoverTab[57064]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:450
			// _ = "end of CoverTab[57064]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:450
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:450
		// _ = "end of CoverTab[57061]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:450
		_go_fuzz_dep_.CoverTab[57062]++
														if !rv.IsNil() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:451
			_go_fuzz_dep_.CoverTab[57065]++
															rv = rv.Elem()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:452
			// _ = "end of CoverTab[57065]"
		} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:453
			_go_fuzz_dep_.CoverTab[57066]++
															rv = reflect.Zero(rv.Type().Elem())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:454
			// _ = "end of CoverTab[57066]"
		}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:455
		// _ = "end of CoverTab[57062]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:456
		_go_fuzz_dep_.CoverTab[57067]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:456
		// _ = "end of CoverTab[57067]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:456
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:456
	// _ = "end of CoverTab[57056]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:456
	_go_fuzz_dep_.CoverTab[57057]++
													if rv.Type() != c.goType {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:457
		_go_fuzz_dep_.CoverTab[57068]++
														panic(fmt.Sprintf("invalid type: got %v, want %v", rv.Type(), c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:458
		// _ = "end of CoverTab[57068]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:459
		_go_fuzz_dep_.CoverTab[57069]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:459
		// _ = "end of CoverTab[57069]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:459
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:459
	// _ = "end of CoverTab[57057]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:459
	_go_fuzz_dep_.CoverTab[57058]++
													return rv
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:460
	// _ = "end of CoverTab[57058]"
}

func (c *messageConverter) IsValidPB(v protoreflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:463
	_go_fuzz_dep_.CoverTab[57070]++
													m := v.Message()
													var rv reflect.Value
													if u, ok := m.(unwrapper); ok {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:466
		_go_fuzz_dep_.CoverTab[57073]++
														rv = reflect.ValueOf(u.protoUnwrap())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:467
		// _ = "end of CoverTab[57073]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:468
		_go_fuzz_dep_.CoverTab[57074]++
														rv = reflect.ValueOf(m.Interface())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:469
		// _ = "end of CoverTab[57074]"
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:470
	// _ = "end of CoverTab[57070]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:470
	_go_fuzz_dep_.CoverTab[57071]++
													if c.isNonPointer() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:471
		_go_fuzz_dep_.CoverTab[57075]++
														return rv.Type() == reflect.PtrTo(c.goType)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:472
		// _ = "end of CoverTab[57075]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:473
		_go_fuzz_dep_.CoverTab[57076]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:473
		// _ = "end of CoverTab[57076]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:473
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:473
	// _ = "end of CoverTab[57071]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:473
	_go_fuzz_dep_.CoverTab[57072]++
													return rv.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:474
	// _ = "end of CoverTab[57072]"
}

func (c *messageConverter) IsValidGo(v reflect.Value) bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:477
	_go_fuzz_dep_.CoverTab[57077]++
													return v.IsValid() && func() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:478
		_go_fuzz_dep_.CoverTab[57078]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:478
		return v.Type() == c.goType
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:478
		// _ = "end of CoverTab[57078]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:478
	}()
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:478
	// _ = "end of CoverTab[57077]"
}

func (c *messageConverter) New() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:481
	_go_fuzz_dep_.CoverTab[57079]++
													if c.isNonPointer() {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:482
		_go_fuzz_dep_.CoverTab[57081]++
														return c.PBValueOf(reflect.New(c.goType).Elem())
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:483
		// _ = "end of CoverTab[57081]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:484
		_go_fuzz_dep_.CoverTab[57082]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:484
		// _ = "end of CoverTab[57082]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:484
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:484
	// _ = "end of CoverTab[57079]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:484
	_go_fuzz_dep_.CoverTab[57080]++
													return c.PBValueOf(reflect.New(c.goType.Elem()))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:485
	// _ = "end of CoverTab[57080]"
}

func (c *messageConverter) Zero() protoreflect.Value {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:488
	_go_fuzz_dep_.CoverTab[57083]++
													return c.PBValueOf(reflect.Zero(c.goType))
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:489
	// _ = "end of CoverTab[57083]"
}

// isNonPointer reports whether the type is a non-pointer type.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:492
// This never occurs for generated message types.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:494
func (c *messageConverter) isNonPointer() bool {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:494
	_go_fuzz_dep_.CoverTab[57084]++
													return c.goType.Kind() != reflect.Ptr
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:495
	// _ = "end of CoverTab[57084]"
}

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:496
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/convert.go:496
var _ = _go_fuzz_dep_.CoverTab
