// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:5
package impl

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:5
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:5
	_go_fuzz_dep_ "go-fuzz-dep"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:5
)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:5
import (
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:5
	_atomic_ "sync/atomic"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:5
)

import (
	"bytes"
	"compress/gzip"
	"io/ioutil"
	"sync"

	"google.golang.org/protobuf/internal/filedesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
)

// Every enum and message type generated by protoc-gen-go since commit 2fc053c5
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:18
// on February 25th, 2016 has had a method to get the raw descriptor.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:18
// Types that were not generated by protoc-gen-go or were generated prior
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:18
// to that version are not supported.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:18
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:18
// The []byte returned is the encoded form of a FileDescriptorProto message
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:18
// compressed using GZIP. The []int is the path from the top-level file
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:18
// to the specific message or enum declaration.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:26
type (
	enumV1	interface {
		EnumDescriptor() ([]byte, []int)
	}
	messageV1	interface {
		Descriptor() ([]byte, []int)
	}
)

var legacyFileDescCache sync.Map	// map[*byte]protoreflect.FileDescriptor

// legacyLoadFileDesc unmarshals b as a compressed FileDescriptorProto message.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:37
//
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:37
// This assumes that b is immutable and that b does not refer to part of a
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:37
// concatenated series of GZIP files (which would require shenanigans that
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:37
// rely on the concatenation properties of both protobufs and GZIP).
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:37
// File descriptors generated by protoc-gen-go do not rely on that property.
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:43
func legacyLoadFileDesc(b []byte) protoreflect.FileDescriptor {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:43
	_go_fuzz_dep_.CoverTab[57621]++

													if fd, ok := legacyFileDescCache.Load(&b[0]); ok {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:45
		_go_fuzz_dep_.CoverTab[57626]++
														return fd.(protoreflect.FileDescriptor)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:46
		// _ = "end of CoverTab[57626]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:47
		_go_fuzz_dep_.CoverTab[57627]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:47
		// _ = "end of CoverTab[57627]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:47
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:47
	// _ = "end of CoverTab[57621]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:47
	_go_fuzz_dep_.CoverTab[57622]++

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:50
	zr, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:51
		_go_fuzz_dep_.CoverTab[57628]++
														panic(err)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:52
		// _ = "end of CoverTab[57628]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:53
		_go_fuzz_dep_.CoverTab[57629]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:53
		// _ = "end of CoverTab[57629]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:53
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:53
	// _ = "end of CoverTab[57622]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:53
	_go_fuzz_dep_.CoverTab[57623]++
													b2, err := ioutil.ReadAll(zr)
													if err != nil {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:55
		_go_fuzz_dep_.CoverTab[57630]++
														panic(err)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:56
		// _ = "end of CoverTab[57630]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:57
		_go_fuzz_dep_.CoverTab[57631]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:57
		// _ = "end of CoverTab[57631]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:57
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:57
	// _ = "end of CoverTab[57623]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:57
	_go_fuzz_dep_.CoverTab[57624]++

													fd := filedesc.Builder{
		RawDescriptor:	b2,
		FileRegistry:	resolverOnly{protoregistry.GlobalFiles},
	}.Build().File
	if fd, ok := legacyFileDescCache.LoadOrStore(&b[0], fd); ok {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:63
		_go_fuzz_dep_.CoverTab[57632]++
														return fd.(protoreflect.FileDescriptor)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:64
		// _ = "end of CoverTab[57632]"
	} else {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:65
		_go_fuzz_dep_.CoverTab[57633]++
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:65
		// _ = "end of CoverTab[57633]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:65
	}
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:65
	// _ = "end of CoverTab[57624]"
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:65
	_go_fuzz_dep_.CoverTab[57625]++
													return fd
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:66
	// _ = "end of CoverTab[57625]"
}

type resolverOnly struct {
	reg *protoregistry.Files
}

func (r resolverOnly) FindFileByPath(path string) (protoreflect.FileDescriptor, error) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:73
	_go_fuzz_dep_.CoverTab[57634]++
													return r.reg.FindFileByPath(path)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:74
	// _ = "end of CoverTab[57634]"
}
func (r resolverOnly) FindDescriptorByName(name protoreflect.FullName) (protoreflect.Descriptor, error) {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:76
	_go_fuzz_dep_.CoverTab[57635]++
													return r.reg.FindDescriptorByName(name)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:77
	// _ = "end of CoverTab[57635]"
}
func (resolverOnly) RegisterFile(protoreflect.FileDescriptor) error {
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:79
	_go_fuzz_dep_.CoverTab[57636]++
													return nil
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:80
	// _ = "end of CoverTab[57636]"
}

//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:81
var _ = _atomic_.LoadUint32(&_go_fuzz_dep_.NoUse)
//line /home/tianchang/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/legacy_file.go:81
var _ = _go_fuzz_dep_.CoverTab
