# Copyright 2018 Intel Corporation
# Copyright 2018-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

images:
  tags:
    initCU: docker.io/omecproject/pod-init:1.0.0
    nats: registry.aether.opennetworking.org/aether/accelleran-cu-nats-b17:v1.0.0
    redis: registry.aether.opennetworking.org/aether/accelleran-cu-redis-b17:v1.0.0
    vranL3: registry.aether.opennetworking.org/aether/accelleran-cu-l3-fdd-b17:v1.0.0
  pullPolicy: IfNotPresent

nodeSelectors:
  enabled: false
  accelleranCU:
    label: accelleran-cu
    value: enabled

resources:
  enabled: true
  accelleranCU:
    requests:
      cpu: 3
      memory: 1Gi
    limits:
      cpu: 3
      memory: 1Gi

config:
  vran:
    replicas: 1
    socketInterface: eth0
    instId: "enb_key"
    ports:
      s1ap:
        port: 36412
      nats:
        port: 4222
        nodePort: 4222
      redis:
        port: 6379
        nodePort: 6379
  nats:
    serviceName: "nats-cluster"
    ip: 10.90.0.151
  epc:
    plmnId: 371211
  mme:
    ip: 10.90.0.151
    s1apPort: 36412
  progran:
    enabled: false
    # ONOS ProgRAN IP address
    ip: 10.90.0.151
    port: 30410


