---
# Copyright 2018 Intel Corporation
# Copyright 2018-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

apiVersion: v1
description: OMEC control plane services
name: omec-control-plane
icon: https://guide.opencord.org/logos/cord.svg

version: 0.6.21
